// Steam Achievement Database
// Consolidated - Each game appears only once (alphabetically sorted)
// Format: "Game Title": { hasAchievements: boolean, count: number }

const steamAchievements = {
    "60 Parsecs!": { hasAchievements: true, count: 44 },
    "60 Seconds! Reatomized": { hasAchievements: true, count: 60 },
    "7 Days to Die": { hasAchievements: true, count: 43 },
    "A Story About My Uncle": { hasAchievements: true, count: 15 },
    "A Way Out": { hasAchievements: true, count: 14 },
    "Adventure Time: Pirates of the Enchiridion": { hasAchievements: true, count: 36 },
    "Age of Empires III: Definitive Edition": { hasAchievements: true, count: 331 },
    "Alan Wake": { hasAchievements: true, count: 67 },
    "Alan Wake 2": { hasAchievements: true, count: 39 },
    "Alan Wakes American Nightmare": { hasAchievements: true, count: 12 },
    "Alice: Madness Returns": { hasAchievements: false, count: 0 },
    "Alien: Isolation": { hasAchievements: true, count: 50 },
    "American Truck Simulator": { hasAchievements: true, count: 121 },
    "Amnesia: The Dark Descent": { hasAchievements: true, count: 18 },
    "Among Us": { hasAchievements: true, count: 33 },
    "Apex Legends": { hasAchievements: true, count: 12 },
    "ARK: Survival Evolved": { hasAchievements: true, count: 32 },
    "ARK: Survival Of The Fittest": { hasAchievements: false, count: 0 },
    "Arma 3": { hasAchievements: true, count: 123 },
    "Assassin's Creed": { hasAchievements: false, count: 0 },
    "Assassin's Creed Brotherhood": { hasAchievements: false, count: 0 },
    "Assassin's Creed Freedom Cry": { hasAchievements: true, count: 12 },
    "Assassin's Creed II": { hasAchievements: false, count: 0 },
    "Assassin's Creed III": { hasAchievements: true, count: 44 },
    "Assassin's Creed III Remastered": { hasAchievements: true, count: 84 },
    "Assassin's Creed IV Black Flag": { hasAchievements: true, count: 60 },
    "Assassin's Creed Liberation": { hasAchievements: true, count: 30 },
    "Assassin's Creed Odyssey": { hasAchievements: true, count: 93 },
    "Assassin's Creed Origins": { hasAchievements: true, count: 67 },
    "Assassin's Creed Revelations": { hasAchievements: true, count: 48 },
    "Assassin's Creed Rogue": { hasAchievements: true, count: 46 },
    "Assassin's Creed Syndicate": { hasAchievements: true, count: 56 },
    "Assassin's Creed Unity": { hasAchievements: true, count: 57 },
    "Assassin's Creed Valhalla": { hasAchievements: true, count: 92 },
    "Assassin's Creed® Chronicles: China": { hasAchievements: true, count: 18 },
    "Assassin's Creed® Chronicles: India": { hasAchievements: true, count: 18 },
    "Assassin's Creed® Chronicles: Russia": { hasAchievements: true, count: 17 },
    "Assassin's Creed® III": { hasAchievements: true, count: 44 },
    "Back 4 Blood": { hasAchievements: true, count: 93 },
    "Baldur's Gate 3": { hasAchievements: true, count: 54 },
    "Batman - The Telltale Series": { hasAchievements: true, count: 30 },
    "Batman: Arkham Asylum GOTY Edition": { hasAchievements: true, count: 47 },
    "Batman: Arkham City GOTY": { hasAchievements: true, count: 64 },
    "Batman: The Enemy Within": { hasAchievements: false, count: 0 },
    "Batman: The Enemy Within - The Telltale Series": { hasAchievements: true, count: 30 },
    "Batman™: Arkham Knight": { hasAchievements: true, count: 113 },
    "Batman™: Arkham Origins": { hasAchievements: true, count: 60 },
    "Batman™: Arkham Origins Blackgate - Deluxe Edition": { hasAchievements: true, count: 30 },
    "BattleBit Remastered": { hasAchievements: false, count: 0 },
    "BattleBlock Theater": { hasAchievements: true, count: 30 },
    "Battlefield 3™": { hasAchievements: true, count: 34 },
    "Battlefield 4™": { hasAchievements: true, count: 67 },
    "Battlefield Hardline": { hasAchievements: true, count: 62 },
    "Battlefield™ 1": { hasAchievements: true, count: 50 },
    "Battlefield™ 2042": { hasAchievements: true, count: 34 },
    "Battlefield™ V": { hasAchievements: true, count: 21 },
    "Beyond: Two Souls": { hasAchievements: true, count: 45 },
    "BIOMUTANT": { hasAchievements: false, count: 0 },
    "BioShock": { hasAchievements: false, count: 0 },
    "BioShock 2": { hasAchievements: true, count: 68 },
    "BioShock 2 Remastered": { hasAchievements: true, count: 53 },
    "BioShock Infinite": { hasAchievements: true, count: 80 },
    "BioShock Remastered": { hasAchievements: true, count: 65 },
    "Black Desert": { hasAchievements: false, count: 0 },
    "Blood and Bacon": { hasAchievements: true, count: 42 },
    "Bloons TD 6": { hasAchievements: true, count: 153 },
    "Borderlands 2": { hasAchievements: true, count: 75 },
    "Borderlands 3": { hasAchievements: true, count: 81 },
    "Borderlands GOTY": { hasAchievements: true, count: 80 },
    "Borderlands GOTY Enhanced": { hasAchievements: true, count: 80 },
    "Borderlands: The Pre-Sequel": { hasAchievements: true, count: 63 },
    "Brotato": { hasAchievements: true, count: 176 },
    "Bully: Scholarship Edition": { hasAchievements: false, count: 0 },
    "Burg": { hasAchievements: false, count: 0 },
    "Burnout™ Paradise Remastered": { hasAchievements: true, count: 56 },
    "Call of Duty (2003)": { hasAchievements: false, count: 0 },
    "Call of Duty 2": { hasAchievements: false, count: 0 },
    "Call of Duty 4: Modern Warfare (2007)": { hasAchievements: false, count: 0 },
    "Call of Duty: Advanced Warfare": { hasAchievements: true, count: 45 },
    "Call of Duty: Advanced Warfare - Multiplayer": { hasAchievements: true, count: 45 },
    "Call of Duty: Black Ops": { hasAchievements: true, count: 68 },
    "Call of Duty: Black Ops - Multiplayer": { hasAchievements: true, count: 3 },
    "Call of Duty: Black Ops II": { hasAchievements: true, count: 35 },
    "Call of Duty: Black Ops II - Multiplayer": { hasAchievements: true, count: 5 },
    "Call of Duty: Black Ops II - Zombies": { hasAchievements: true, count: 50 },
    "Call of Duty: Black Ops III": { hasAchievements: true, count: 98 },
    "Call of Duty: Ghosts": { hasAchievements: true, count: 40 },
    "Call of Duty: Ghosts - Multiplayer": { hasAchievements: true, count: 51 },
    "Call of Duty: Infinite Warfare": { hasAchievements: true, count: 88 },
    "Call of Duty: Modern Warfare 2 (2009)": { hasAchievements: true, count: 50 },
    "Call of Duty: Modern Warfare 2 (2009) - Multiplayer": { hasAchievements: false, count: 0 },
    "Call of Duty: Modern Warfare Remastered - Multiplayer": { hasAchievements: false, count: 0 },
    "Call of Duty: Modern Warfare Remastered (2017)": { hasAchievements: true, count: 50 },
    "Call of Duty: United Offensive": { hasAchievements: false, count: 0 },
    "Call of Duty: World at War": { hasAchievements: false, count: 0 },
    "Call of Duty: WWII": { hasAchievements: true, count: 35 },
    "Call of Duty: WWII - Multiplayer": { hasAchievements: true, count: 55 },
    "Call of Duty®": { hasAchievements: true, count: 27 },
    "Call of Duty®: Black Ops Cold War": { hasAchievements: true, count: 44 },
    "Call of Duty®: Modern Warfare®": { hasAchievements: true, count: 27 },
    "Call of Duty®: Modern Warfare® 3 (2011)": { hasAchievements: true, count: 76 },
    "Call of Duty®: Modern Warfare® 3 (2011) - Multiplayer": { hasAchievements: false, count: 0 },
    "Call of Duty®: Modern Warfare® II": { hasAchievements: true, count: 24 },
    "Call of Duty®: Modern Warfare® II - Open Beta": { hasAchievements: false, count: 0 },
    "Call of Duty®: Modern Warfare® III": { hasAchievements: true, count: 39 },
    "Call of Duty®: Vanguard": { hasAchievements: true, count: 44 },
    "Capcom Fighting Collection": { hasAchievements: true, count: 45 },
    "Castle Crashers": { hasAchievements: true, count: 12 },
    "Celeste": { hasAchievements: true, count: 32 },
    "Chained Together": { hasAchievements: true, count: 16 },
    "Clustertruck": { hasAchievements: true, count: 19 },
    "Comedy Night": { hasAchievements: false, count: 0 },
    "Company of Heroes 2": { hasAchievements: true, count: 452 },
    "Content Warning": { hasAchievements: true, count: 48 },
    "Contra Anniversary Collection": { hasAchievements: true, count: 16 },
    "Control Ultimate Edition": { hasAchievements: true, count: 67 },
    "Cookie Clicker": { hasAchievements: true, count: 637 },
    "Counter-Strike": { hasAchievements: false, count: 0 },
    "Counter-Strike 2": { hasAchievements: true, count: 1 },
    "Counter-Strike: Condition Zero": { hasAchievements: false, count: 0 },
    "Counter-Strike: Condition Zero Deleted Scenes": { hasAchievements: false, count: 0 },
    "Counter-Strike: Source": { hasAchievements: true, count: 147 },
    "Crab Game": { hasAchievements: false, count: 0 },
    "Crash Bandicoot™ N. Sane Trilogy": { hasAchievements: true, count: 74 },
    "Crusader Kings II": { hasAchievements: false, count: 0 },
    "Crysis Warhead®": { hasAchievements: false, count: 0 },
    "Cult of the Lamb": { hasAchievements: true, count: 48 },
    "Cuphead": { hasAchievements: true, count: 42 },
    "Cyberpunk 2077": { hasAchievements: true, count: 57 },
    "Darkest Dungeon®": { hasAchievements: true, count: 120 },
    "Darwin Project": { hasAchievements: true, count: 14 },
    "Day of Defeat": { hasAchievements: false, count: 0 },
    "Day of Defeat: Source": { hasAchievements: true, count: 54 },
    "Days Gone": { hasAchievements: true, count: 67 },
    "DayZ": { hasAchievements: true, count: 13 },
    "Dead by Daylight": { hasAchievements: true, count: 288 },
    "Dead Cells": { hasAchievements: true, count: 121 },
    "Dead Island Definitive Edition": { hasAchievements: true, count: 57 },
    "Dead Island Retro Revenge": { hasAchievements: true, count: 13 },
    "Dead Island Riptide Definitive Edition": { hasAchievements: true, count: 35 },
    "Dead Rising": { hasAchievements: true, count: 50 },
    "Dead Rising 2": { hasAchievements: true, count: 50 },
    "Dead Rising 2: Off the Record": { hasAchievements: true, count: 50 },
    "Dead Rising 3": { hasAchievements: true, count: 88 },
    "Dead Rising 4": { hasAchievements: true, count: 104 },
    "Dead Space": { hasAchievements: true, count: 47 },
    "Dead Space (2008)": { hasAchievements: true, count: 47 },
    "Dead Space 2": { hasAchievements: false, count: 0 },
    "Dead Space™ 3": { hasAchievements: true, count: 58 },
    "DEATH STRANDING DIRECTOR'S CUT": { hasAchievements: true, count: 63 },
    "DEATHLOOP": { hasAchievements: true, count: 58 },
    "Deathmatch Classic": { hasAchievements: false, count: 0 },
    "Deceit": { hasAchievements: true, count: 14 },
    "Deep Rock Galactic": { hasAchievements: true, count: 69 },
    "Destroy All Humans!": { hasAchievements: true, count: 40 },
    "Destroy All Humans! 2 - Reprobed": { hasAchievements: true, count: 44 },
    "Detroit: Become Human": { hasAchievements: true, count: 48 },
    "Deus Ex: Human Revolution - Director's Cut": { hasAchievements: true, count: 59 },
    "Deus Ex: Mankind Divided™": { hasAchievements: true, count: 81 },
    "Deus Ex: The Fall": { hasAchievements: true, count: 28 },
    "Devolverland Expo": { hasAchievements: true, count: 22 },
    "Dishonored": { hasAchievements: true, count: 80 },
    "Dishonored 2": { hasAchievements: true, count: 50 },
    "Divinity: Original Sin 2 - Definitive Edition": { hasAchievements: true, count: 97 },
    "Don't Starve": { hasAchievements: false, count: 0 },
    "Don't Starve Together": { hasAchievements: false, count: 0 },
    "Donut County": { hasAchievements: true, count: 20 },
    "DOOM": { hasAchievements: true, count: 54 },
    "DOOM + DOOM II": { hasAchievements: true, count: 33 },
    "DOOM 3": { hasAchievements: false, count: 0 },
    "DOOM 3: BFG Edition": { hasAchievements: true, count: 65 },
    "DOOM 64": { hasAchievements: true, count: 10 },
    "DOOM Eternal": { hasAchievements: true, count: 50 },
    "DOOM II": { hasAchievements: false, count: 0 },
    "Dota 2": { hasAchievements: false, count: 0 },
    "Drug Dealer Simulator": { hasAchievements: true, count: 36 },
    "Dungeon Defenders": { hasAchievements: true, count: 118 },
    "Dungeon Defenders II": { hasAchievements: true, count: 18 },
    "Dying Light": { hasAchievements: true, count: 78 },
    "Dying Light 2: Reloaded Edition": { hasAchievements: true, count: 65 },
    "EARTH DEFENSE FORCE 5": { hasAchievements: true, count: 36 },
    "ELDEN RING": { hasAchievements: true, count: 42 },
    "Enter the Gungeon": { hasAchievements: true, count: 54 },
    "Escape Dead Island": { hasAchievements: true, count: 60 },
    "Escape Memoirs: Mini Stories": { hasAchievements: true, count: 15 },
    "Escape Simulator": { hasAchievements: true, count: 25 },
    "Escape the Backrooms": { hasAchievements: true, count: 30 },
    "Euro Truck Simulator 2": { hasAchievements: true, count: 101 },
    "Exit the Gungeon": { hasAchievements: true, count: 47 },
    "Fable Anniversary": { hasAchievements: true, count: 50 },
    "Factorio": { hasAchievements: true, count: 88 },
    "Fall Guys": { hasAchievements: true, count: 34 },
    "Fallout": { hasAchievements: false, count: 0 },
    "Fallout 2": { hasAchievements: false, count: 0 },
    "Fallout 3 - Game of the Year Edition": { hasAchievements: false, count: 0 },
    "Fallout 4": { hasAchievements: true, count: 84 },
    "Fallout 76": { hasAchievements: true, count: 84 },
    "Fallout Shelter": { hasAchievements: true, count: 35 },
    "Fallout: New Vegas": { hasAchievements: true, count: 75 },
    "Far Cry 3": { hasAchievements: true, count: 44 },
    "Far Cry 3 Blood Dragon": { hasAchievements: true, count: 19 },
    "Far Cry 4": { hasAchievements: true, count: 57 },
    "Far Cry 5": { hasAchievements: true, count: 72 },
    "Far Cry 6": { hasAchievements: true, count: 99 },
    "Far Cry New Dawn": { hasAchievements: true, count: 50 },
    "Far Cry Primal": { hasAchievements: true, count: 55 },
    "Fears to Fathom - Carson House": { hasAchievements: true, count: 5 },
    "Fears to Fathom - Home Alone": { hasAchievements: true, count: 3 },
    "Fears to Fathom - Ironbark Lookout": { hasAchievements: true, count: 5 },
    "Fears to Fathom - Norwood Hitchhike": { hasAchievements: true, count: 6 },
    "Fears to Fathom - Woodbury Getaway": { hasAchievements: true, count: 10 },
    "FINAL FANTASY": { hasAchievements: true, count: 24 },
    "FINAL FANTASY II": { hasAchievements: true, count: 28 },
    "FINAL FANTASY III": { hasAchievements: true, count: 31 },
    "FINAL FANTASY IV": { hasAchievements: true, count: 30 },
    "FINAL FANTASY IX": { hasAchievements: true, count: 85 },
    "FINAL FANTASY TYPE-0 HD": { hasAchievements: true, count: 49 },
    "FINAL FANTASY V": { hasAchievements: true, count: 39 },
    "FINAL FANTASY VI": { hasAchievements: true, count: 37 },
    "FINAL FANTASY VII": { hasAchievements: true, count: 36 },
    "FINAL FANTASY XII THE ZODIAC AGE": { hasAchievements: true, count: 41 },
    "FINAL FANTASY XIII": { hasAchievements: true, count: 35 },
    "FINAL FANTASY XIII-2": { hasAchievements: true, count: 31 },
    "FINAL FANTASY XV WINDOWS EDITION": { hasAchievements: true, count: 97 },
    "Firewatch": { hasAchievements: true, count: 10 },
    "Five Nights at Freddy's": { hasAchievements: false, count: 0 },
    "Five Nights at Freddy's 2": { hasAchievements: false, count: 0 },
    "Five Nights at Freddy's 3": { hasAchievements: false, count: 0 },
    "For Honor": { hasAchievements: true, count: 60 },
    "Forza Horizon 5": { hasAchievements: true, count: 164 },
    "Friday the 13th: The Game": { hasAchievements: true, count: 53 },
    "Frostpunk": { hasAchievements: true, count: 115 },
    "Gang Beasts": { hasAchievements: true, count: 19 },
    "Garry's Mod": { hasAchievements: true, count: 29 },
    "Genital Jousting": { hasAchievements: true, count: 28 },
    "Geometry Dash": { hasAchievements: true, count: 120 },
    "Getting Over It with Bennett Foddy": { hasAchievements: true, count: 3 },
    "Goat Simulator": { hasAchievements: true, count: 127 },
    "God of War": { hasAchievements: true, count: 37 },
    "Golf It!": { hasAchievements: true, count: 44 },
    "Golf With Your Friends": { hasAchievements: true, count: 83 },
    "Goose Goose Duck": { hasAchievements: true, count: 38 },
    "Grand Theft Auto III": { hasAchievements: false, count: 0 },
    "Grand Theft Auto III - The Definitive Edition": { hasAchievements: true, count: 29 },
    "Grand Theft Auto IV: The Complete Edition": { hasAchievements: true, count: 55 },
    "Grand Theft Auto V": { hasAchievements: true, count: 77 },
    "Grand Theft Auto V Enhanced": { hasAchievements: true, count: 77 },
    "Grand Theft Auto V Legacy": { hasAchievements: true, count: 77 },
    "Grand Theft Auto: San Andreas": { hasAchievements: false, count: 0 },
    "Grand Theft Auto: San Andreas - The Definitive Edition": { hasAchievements: true, count: 35 },
    "Grand Theft Auto: Vice City": { hasAchievements: false, count: 0 },
    "Grand Theft Auto: Vice City - The Definitive Edition": { hasAchievements: true, count: 34 },
    "Graveyard Keeper": { hasAchievements: true, count: 125 },
    "GRIS": { hasAchievements: true, count: 17 },
    "Grounded": { hasAchievements: true, count: 45 },
    "Grow Home": { hasAchievements: true, count: 24 },
    "Grow Up": { hasAchievements: true, count: 18 },
    "GTFO": { hasAchievements: true, count: 57 },
    "GUNDAM EVOLUTION": { hasAchievements: true, count: 12 },
    "Hades": { hasAchievements: true, count: 49 },
    "Half-Life": { hasAchievements: false, count: 0 },
    "Half-Life 2": { hasAchievements: true, count: 69 },
    "Half-Life 2: Deathmatch": { hasAchievements: false, count: 0 },
    "Half-Life Deathmatch: Source": { hasAchievements: false, count: 0 },
    "Half-Life: Blue Shift": { hasAchievements: false, count: 0 },
    "Half-Life: Opposing Force": { hasAchievements: false, count: 0 },
    "Half-Life: Source": { hasAchievements: false, count: 0 },
    "Halo Infinite": { hasAchievements: true, count: 144 },
    "Halo Wars: Definitive Edition": { hasAchievements: true, count: 75 },
    "Halo: Spartan Assault": { hasAchievements: true, count: 25 },
    "Halo: Spartan Strike": { hasAchievements: true, count: 20 },
    "Halo: The Master Chief Collection": { hasAchievements: true, count: 700 },
    "Hand Simulator": { hasAchievements: true, count: 72 },
    "Hand Simulator: Survival": { hasAchievements: true, count: 7 },
    "Heavy Rain": { hasAchievements: true, count: 56 },
    "Hellblade: Senua's Sacrifice": { hasAchievements: true, count: 14 },
    "Hellblade: Senua's Sacrifice VR Edition": { hasAchievements: true, count: 14 },
    "HELLDIVERS™": { hasAchievements: true, count: 39 },
    "HELLDIVERS™ 2": { hasAchievements: true, count: 38 },
    "Hello Neighbor": { hasAchievements: true, count: 17 },
    "High on Life": { hasAchievements: true, count: 44 },
    "Hitman GO: Definitive Edition": { hasAchievements: true, count: 26 },
    "HITMAN World of Assassination": { hasAchievements: true, count: 83 },
    "Hitman: Absolution": { hasAchievements: true, count: 47 },
    "Hitman: Sniper Challenge": { hasAchievements: false, count: 0 },
    "HITMAN™": { hasAchievements: true, count: 69 },
    "HITMAN™ 2": { hasAchievements: true, count: 146 },
    "Hogwarts Legacy": { hasAchievements: true, count: 45 },
    "Hollow Knight": { hasAchievements: true, count: 63 },
    "Hollow Knight: Silksong": { hasAchievements: true, count: 52 },
    "Horizon Zero Dawn™ Complete Edition": { hasAchievements: true, count: 79 },
    "Hotline Miami": { hasAchievements: true, count: 35 },
    "Hotline Miami 2: Wrong Number": { hasAchievements: true, count: 29 },
    "House Flipper": { hasAchievements: true, count: 96 },
    "House Party": { hasAchievements: true, count: 83 },
    "Human Fall Flat": { hasAchievements: true, count: 143 },
    "Hunt: Showdown 1896": { hasAchievements: true, count: 36 },
    "I Am Bread": { hasAchievements: true, count: 35 },
    "In Silence": { hasAchievements: true, count: 20 },
    "Injustice: Gods Among Us Ultimate Edition": { hasAchievements: true, count: 50 },
    "Injustice™ 2": { hasAchievements: true, count: 74 },
    "Inscryption": { hasAchievements: true, count: 47 },
    "INSIDE": { hasAchievements: true, count: 14 },
    "It Takes Two": { hasAchievements: false, count: 0 },
    "Just Cause": { hasAchievements: false, count: 0 },
    "Just Cause 2": { hasAchievements: true, count: 50 },
    "Just Cause 3": { hasAchievements: true, count: 66 },
    "Just Cause 4": { hasAchievements: true, count: 61 },
    "Keep Talking and Nobody Explodes": { hasAchievements: true, count: 10 },
    "Killing Floor": { hasAchievements: true, count: 285 },
    "Killing Floor 2": { hasAchievements: true, count: 307 },
    "Kingdom Come: Deliverance": { hasAchievements: true, count: 82 },
    "Lara Croft and the Guardian of Light": { hasAchievements: true, count: 12 },
    "Lara Croft and the Temple of Osiris": { hasAchievements: true, count: 40 },
    "Lara Croft GO": { hasAchievements: true, count: 17 },
    "Left 4 Dead": { hasAchievements: true, count: 73 },
    "Left 4 Dead 2": { hasAchievements: true, count: 101 },
    "LEGO® Batman™ 2: DC Super Heroes": { hasAchievements: false, count: 0 },
    "LEGO® Batman™ 3: Beyond Gotham": { hasAchievements: true, count: 70 },
    "LEGO® Batman™: The Videogame": { hasAchievements: false, count: 0 },
    "LEGO® Builder's Journey": { hasAchievements: true, count: 22 },
    "LEGO® City Undercover": { hasAchievements: true, count: 48 },
    "LEGO® DC Super-Villains": { hasAchievements: true, count: 75 },
    "LEGO® Harry Potter: Years 1-4": { hasAchievements: false, count: 0 },
    "LEGO® Harry Potter: Years 5-7": { hasAchievements: false, count: 0 },
    "LEGO® Harry Potter™ Collection": { hasAchievements: true, count: 84 },
    "LEGO® Indiana Jones™ 2: The Adventure Continues": { hasAchievements: false, count: 0 },
    "LEGO® Jurassic World": { hasAchievements: true, count: 45 },
    "LEGO® MARVEL Super Heroes": { hasAchievements: true, count: 45 },
    "LEGO® MARVEL Super Heroes 2": { hasAchievements: true, count: 50 },
    "LEGO® MARVEL's Avengers": { hasAchievements: true, count: 70 },
    "LEGO® Pirates of the Caribbean The Video Game": { hasAchievements: false, count: 0 },
    "LEGO® Star Wars™ III: The Clone Wars™": { hasAchievements: false, count: 0 },
    "LEGO® Star Wars™: The Complete Saga": { hasAchievements: false, count: 0 },
    "LEGO® STAR WARS™: The Force Awakens": { hasAchievements: true, count: 69 },
    "LEGO® Star Wars™: The Skywalker Saga": { hasAchievements: true, count: 45 },
    "LEGO® The Hobbit™": { hasAchievements: true, count: 39 },
    "LEGO® The Incredibles": { hasAchievements: true, count: 45 },
    "LEGO® The LEGO® Movie - Videogame": { hasAchievements: true, count: 48 },
    "LEGO® The LEGO® Movie 2 - Videogame": { hasAchievements: true, count: 50 },
    "LEGO® The LEGO® NINJAGO® Movie Video Game": { hasAchievements: true, count: 50 },
    "LEGO® The Lord of the Rings™": { hasAchievements: true, count: 48 },
    "LEGO® Worlds": { hasAchievements: true, count: 71 },
    "LEGOⓇ Indiana Jones™: The Original Adventures": { hasAchievements: false, count: 0 },
    "Lethal Company": { hasAchievements: false, count: 0 },
    "Life is Strange 2": { hasAchievements: true, count: 46 },
    "Life is Strange Remastered": { hasAchievements: true, count: 60 },
    "Life is Strange: Before the Storm": { hasAchievements: true, count: 34 },
    "Life is Strange: Before the Storm Remastered": { hasAchievements: true, count: 34 },
    "Life is Strange: True Colors": { hasAchievements: true, count: 40 },
    "Life is Strange™": { hasAchievements: true, count: 60 },
    "LIGHTNING RETURNS: FINAL FANTASY XIII": { hasAchievements: true, count: 53 },
    "LIMBO": { hasAchievements: true, count: 13 },
    "Little Nightmares": { hasAchievements: true, count: 22 },
    "Little Nightmares II": { hasAchievements: true, count: 35 },
    "LOCKDOWN Protocol": { hasAchievements: false, count: 0 },
    "Longvinter": { hasAchievements: true, count: 49 },
    "Mad Max": { hasAchievements: true, count: 49 },
    "Mafia": { hasAchievements: false, count: 0 },
    "Mafia II (Classic)": { hasAchievements: true, count: 67 },
    "Mafia II: Definitive Edition": { hasAchievements: false, count: 0 },
    "Mafia III: Definitive Edition": { hasAchievements: false, count: 0 },
    "Mafia: Definitive Edition": { hasAchievements: true, count: 43 },
    "Mage Arena": { hasAchievements: false, count: 0 },
    "Marvel Rivals": { hasAchievements: true, count: 49 },
    "Marvel vs. Capcom: Infinite": { hasAchievements: true, count: 47 },
    "Marvel's Avengers - The Definitive Edition": { hasAchievements: true, count: 50 },
    "Marvel's Guardians of the Galaxy": { hasAchievements: true, count: 59 },
    "Marvel's Spider-Man Remastered": { hasAchievements: true, count: 78 },
    "Marvel's Spider-Man: Miles Morales": { hasAchievements: true, count: 50 },
    "Mass Effect™ Legendary Edition": { hasAchievements: true, count: 127 },
    "Max Payne": { hasAchievements: false, count: 0 },
    "Max Payne 2: The Fall of Max Payne": { hasAchievements: false, count: 0 },
    "Max Payne 3": { hasAchievements: true, count: 67 },
    "MechWarrior Online": { hasAchievements: true, count: 36 },
    "Metro 2033 Redux": { hasAchievements: true, count: 49 },
    "Metro Exodus": { hasAchievements: true, count: 68 },
    "Metro Exodus Enhanced Edition": { hasAchievements: true, count: 68 },
    "Metro: Last Light Complete Edition": { hasAchievements: true, count: 70 },
    "Metro: Last Light Redux": { hasAchievements: true, count: 49 },
    "MiniRoyale": { hasAchievements: true, count: 31 },
    "Mirror's Edge": { hasAchievements: false, count: 0 },
    "Mirror's Edge™ Catalyst": { hasAchievements: true, count: 49 },
    "Monopoly Plus": { hasAchievements: false, count: 0 },
    "Monster Hunter: World": { hasAchievements: true, count: 100 },
    "Moonlighter": { hasAchievements: true, count: 68 },
    "Mortal Kombat 11": { hasAchievements: true, count: 58 },
    "Mortal Kombat X": { hasAchievements: true, count: 73 },
    "MultiVersus": { hasAchievements: true, count: 28 },
    "Murderous Pursuits": { hasAchievements: true, count: 17 },
    "My Friend Pedro": { hasAchievements: true, count: 30 },
    "NBA 2K24": { hasAchievements: true, count: 50 },
    "Need for Speed™": { hasAchievements: true, count: 45 },
    "Need for Speed™ Heat": { hasAchievements: true, count: 42 },
    "Need for Speed™ Hot Pursuit Remastered": { hasAchievements: true, count: 66 },
    "Need for Speed™ Most Wanted": { hasAchievements: false, count: 0 },
    "Need for Speed™ Payback": { hasAchievements: true, count: 57 },
    "Need for Speed™ Rivals": { hasAchievements: false, count: 0 },
    "Need for Speed™ Unbound": { hasAchievements: true, count: 41 },
    "Never Alone (Kisima Ingitchuna)": { hasAchievements: true, count: 19 },
    "New Tales from the Borderlands": { hasAchievements: true, count: 26 },
    "NieR:Automata™": { hasAchievements: true, count: 47 },
    "No Man's Sky": { hasAchievements: true, count: 27 },
    "Ori and the Blind Forest": { hasAchievements: true, count: 50 },
    "Ori and the Blind Forest: Definitive Edition": { hasAchievements: true, count: 50 },
    "Ori and the Will of the Wisps": { hasAchievements: true, count: 37 },
    "Outlast": { hasAchievements: true, count: 14 },
    "Outlast 2": { hasAchievements: true, count: 24 },
    "Overcooked": { hasAchievements: true, count: 12 },
    "Overcooked! 2": { hasAchievements: true, count: 54 },
    "Overwatch® 2": { hasAchievements: true, count: 164 },
    "Pacify": { hasAchievements: true, count: 52 },
    "Palworld": { hasAchievements: true, count: 56 },
    "Payday 2": { hasAchievements: true, count: 1328 },
    "PC Building Simulator": { hasAchievements: true, count: 94 },
    "PEAK": { hasAchievements: true, count: 43 },
    "Phasmophobia": { hasAchievements: true, count: 54 },
    "PICO PARK": { hasAchievements: false, count: 0 },
    "Planet Coaster": { hasAchievements: true, count: 32 },
    "Plants vs. Zombies: Battle for Neighborville": { hasAchievements: true, count: 50 },
    "Plants vs. Zombies: Game of the Year": { hasAchievements: true, count: 21 },
    "Plants vs. Zombies™ Garden Warfare 2: Deluxe Edition": { hasAchievements: true, count: 63 },
    "PlayerUnknown's Battlegrounds": { hasAchievements: true, count: 37 },
    "Portal": { hasAchievements: true, count: 15 },
    "Portal 2": { hasAchievements: true, count: 51 },
    "Portal with RTX": { hasAchievements: true, count: 15 },
    "PowerWash Simulator": { hasAchievements: true, count: 100 },
    "Prey": { hasAchievements: true, count: 58 },
    "Project Zomboid": { hasAchievements: false, count: 0 },
    "PROTOTYPE 2": { hasAchievements: true, count: 43 },
    "PUBG: BATTLEGROUNDS": { hasAchievements: true, count: 37 },
    "Pummel Party": { hasAchievements: true, count: 31 },
    "Punch Club": { hasAchievements: true, count: 47 },
    "Quake Champions": { hasAchievements: true, count: 52 },
    "R.E.P.O": { hasAchievements: false, count: 0 },
    "Raft": { hasAchievements: true, count: 104 },
    "RAGE": { hasAchievements: true, count: 60 },
    "RAGE 2": { hasAchievements: true, count: 64 },
    "Rainbow Six Siege": { hasAchievements: false, count: 0 },
    "Rayman Legends": { hasAchievements: true, count: 42 },
    "Red Dead Redemption": { hasAchievements: true, count: 51 },
    "Red Dead Redemption 2": { hasAchievements: true, count: 51 },
    "Resident Evil": { hasAchievements: true, count: 44 },
    "Resident Evil 0": { hasAchievements: true, count: 47 },
    "Resident Evil 2": { hasAchievements: true, count: 44 },
    "Resident Evil 3": { hasAchievements: true, count: 32 },
    "Resident Evil 4 (2005)": { hasAchievements: true, count: 12 },
    "Resident Evil 5": { hasAchievements: true, count: 70 },
    "Resident Evil 6": { hasAchievements: true, count: 70 },
    "Resident Evil 7 Biohazard": { hasAchievements: true, count: 58 },
    "Resident Evil Re:Verse": { hasAchievements: true, count: 12 },
    "RESIDENT EVIL RESISTANCE": { hasAchievements: true, count: 51 },
    "Resident Evil Revelations": { hasAchievements: true, count: 50 },
    "Resident Evil Revelations 2": { hasAchievements: true, count: 43 },
    "Resident Evil Village": { hasAchievements: true, count: 56 },
    "Ricochet": { hasAchievements: false, count: 0 },
    "RimWorld": { hasAchievements: true, count: 92 },
    "Rise of the Tomb Raider": { hasAchievements: true, count: 143 },
    "Risk of Rain (2013)": { hasAchievements: true, count: 15 },
    "RoboCop: Rogue City": { hasAchievements: false, count: 0 },
    "Roboquest": { hasAchievements: false, count: 0 },
    "Rust": { hasAchievements: true, count: 92 },
    "Rust - Staging Branch": { hasAchievements: true, count: 6 },
    "S.T.A.L.K.E.R.: Call of Pripyat": { hasAchievements: false, count: 0 },
    "S.T.A.L.K.E.R.: Clear Sky": { hasAchievements: false, count: 0 },
    "S.T.A.L.K.E.R.: Shadow of Chernobyl": { hasAchievements: false, count: 0 },
    "Saints Row": { hasAchievements: true, count: 64 },
    "Saints Row 2": { hasAchievements: false, count: 0 },
    "Saints Row IV": { hasAchievements: true, count: 73 },
    "Saints Row The Third Remastered": { hasAchievements: true, count: 79 },
    "Saints Row: Gat out of Hell": { hasAchievements: true, count: 45 },
    "Saints Row: The Third": { hasAchievements: true, count: 83 },
    "Scooby-Doo! & Looney Tunes Cartoon Universe: Adventure": { hasAchievements: false, count: 0 },
    "Scott Pilgrim vs The World": { hasAchievements: true, count: 19 },
    "Scribblenauts Unlimited": { hasAchievements: true, count: 25 },
    "Scribblenauts Unmasked": { hasAchievements: true, count: 40 },
    "Sea of Thieves": { hasAchievements: true, count: 283 },
    "SEGA Mega Drive & Genesis Classics": { hasAchievements: true, count: 25 },
    "Sekiro™: Shadows Die Twice": { hasAchievements: true, count: 34 },
    "Shadow of the Tomb Raider": { hasAchievements: true, count: 99 },
    "Shower With Your Dad Simulator 2015": { hasAchievements: true, count: 21 },
    "Sid Meier's Civilization VI": { hasAchievements: true, count: 320 },
    "Slay the Spire": { hasAchievements: true, count: 46 },
    "Sleeping Dogs: Definitive Edition": { hasAchievements: true, count: 59 },
    "Slime Rancher": { hasAchievements: true, count: 57 },
    "Slime Rancher 2": { hasAchievements: true, count: 27 },
    "Sniper Elite 3": { hasAchievements: true, count: 77 },
    "Sniper Elite 4": { hasAchievements: true, count: 85 },
    "Sniper Elite 5": { hasAchievements: true, count: 71 },
    "Sniper Elite V2": { hasAchievements: true, count: 47 },
    "Sniper Elite V2 Remastered": { hasAchievements: true, count: 71 },
    "Sniper Ghost Warrior": { hasAchievements: false, count: 0 },
    "SOMA": { hasAchievements: true, count: 10 },
    "Sonic & All-Stars Racing Transformed Collection": { hasAchievements: true, count: 50 },
    "Sonic Adventure DX": { hasAchievements: true, count: 15 },
    "Sonic Adventure™ 2": { hasAchievements: true, count: 15 },
    "Sonic CD": { hasAchievements: true, count: 12 },
    "Sonic Forces": { hasAchievements: true, count: 48 },
    "Sonic Generations": { hasAchievements: true, count: 49 },
    "Sonic Lost World": { hasAchievements: true, count: 100 },
    "Sonic Mania": { hasAchievements: true, count: 18 },
    "SONIC THE HEDGEHOG 4 Episode I": { hasAchievements: true, count: 12 },
    "SONIC THE HEDGEHOG 4 Episode II": { hasAchievements: true, count: 12 },
    "South Park The Fractured But Whole": { hasAchievements: true, count: 35 },
    "SOUTH PARK: SNOW DAY!": { hasAchievements: true, count: 32 },
    "South Park™: The Stick of Truth™": { hasAchievements: true, count: 50 },
    "SpeedRunners": { hasAchievements: true, count: 29 },
    "Split Fiction": { hasAchievements: true, count: 20 },
    "Splitgate": { hasAchievements: true, count: 30 },
    "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated": { hasAchievements: true, count: 32 },
    "SpongeBob SquarePants: The Cosmic Shake": { hasAchievements: true, count: 44 },
    "Spyro™ Reignited Trilogy": { hasAchievements: true, count: 105 },
    "STAR WARS Jedi: Fallen Order™": { hasAchievements: true, count: 39 },
    "STAR WARS Jedi: Survivor™": { hasAchievements: true, count: 53 },
    "STAR WARS™ Battlefront™": { hasAchievements: true, count: 63 },
    "STAR WARS™ Battlefront™ II": { hasAchievements: true, count: 43 },
    "STAR WARS™: Squadrons": { hasAchievements: true, count: 47 },
    "Starbound": { hasAchievements: true, count: 51 },
    "Stardew Valley": { hasAchievements: true, count: 49 },
    "Stick Fight: The Game": { hasAchievements: true, count: 28 },
    "Street Fighter 30th Anniversary Collection": { hasAchievements: true, count: 17 },
    "Street Fighter V": { hasAchievements: true, count: 45 },
    "Subnautica": { hasAchievements: true, count: 17 },
    "Subnautica: Below Zero": { hasAchievements: true, count: 13 },
    "Suicide Squad: Kill the Justice League": { hasAchievements: true, count: 50 },
    "Sunset Overdrive": { hasAchievements: true, count: 80 },
    "Super Meat Boy": { hasAchievements: true, count: 48 },
    "Surgeon Simulator": { hasAchievements: true, count: 123 },
    "Tales from the Borderlands": { hasAchievements: true, count: 35 },
    "Team Fortress 2": { hasAchievements: true, count: 520 },
    "Team Fortress Classic": { hasAchievements: false, count: 0 },
    "Team Sonic Racing™": { hasAchievements: true, count: 51 },
    "Terraria": { hasAchievements: true, count: 115 },
    "The Awesome Adventures of Captain Spirit": { hasAchievements: false, count: 0 },
    "The Binding of Isaac: Rebirth": { hasAchievements: true, count: 641 },
    "The Crew 2": { hasAchievements: true, count: 34 },
    "The Elder Scrolls III: Morrowind": { hasAchievements: false, count: 0 },
    "The Elder Scrolls IV: Oblivion Game of the Year Edition (2009)": { hasAchievements: false, count: 0 },
    "The Elder Scrolls V: Skyrim Special Edition": { hasAchievements: true, count: 75 },
    "The Elder Scrolls® Online": { hasAchievements: false, count: 0 },
    "The Evil Within": { hasAchievements: true, count: 51 },
    "The Evil Within 2": { hasAchievements: false, count: 0 },
    "The Forest": { hasAchievements: true, count: 45 },
    "THE GAME OF LIFE": { hasAchievements: true, count: 10 },
    "The Lab": { hasAchievements: false, count: 0 },
    "The Last of Us™ Part I": { hasAchievements: true, count: 29 },
    "The Outer Worlds: Spacer's Choice Edition": { hasAchievements: true, count: 68 },
    "The Quarry": { hasAchievements: true, count: 40 },
    "The Sims 4": { hasAchievements: true, count: 75 },
    "The Walking Dead": { hasAchievements: true, count: 48 },
    "The Walking Dead: A New Frontier": { hasAchievements: true, count: 30 },
    "The Walking Dead: Michonne": { hasAchievements: true, count: 18 },
    "The Walking Dead: Season Two": { hasAchievements: true, count: 40 },
    "The Walking Dead: The Final Season": { hasAchievements: true, count: 48 },
    "The Witcher 2: Assassins of Kings Enhanced Edition": { hasAchievements: true, count: 52 },
    "The Witcher 3: Wild Hunt": { hasAchievements: true, count: 78 },
    "The Witcher: Enhanced Edition": { hasAchievements: false, count: 0 },
    "The Wolf Among Us": { hasAchievements: true, count: 35 },
    "theHunter: Call of the Wild™": { hasAchievements: true, count: 160 },
    "Thief": { hasAchievements: true, count: 37 },
    "Tiny Tina's Wonderlands": { hasAchievements: true, count: 47 },
    "Titanfall® 2": { hasAchievements: true, count: 50 },
    "Tom Clancy's EndWar": { hasAchievements: false, count: 0 },
    "Tom Clancy's Ghost Recon": { hasAchievements: false, count: 0 },
    "Tom Clancy's Ghost Recon Future Soldier": { hasAchievements: false, count: 0 },
    "Tom Clancy's Ghost Recon: Desert Siege": { hasAchievements: false, count: 0 },
    "Tom Clancy's Ghost Recon: Island Thunder": { hasAchievements: false, count: 0 },
    "Tom Clancy's Ghost Recon® Wildlands": { hasAchievements: true, count: 57 },
    "Tom Clancy's Rainbow Six 3: Athena Sword": { hasAchievements: false, count: 0 },
    "Tom Clancy's Rainbow Six 3: Gold Edition": { hasAchievements: false, count: 0 },
    "Tom Clancy's Rainbow Six Siege - Test Server": { hasAchievements: false, count: 0 },
    "Tom Clancy's Rainbow Six: Lockdown": { hasAchievements: false, count: 0 },
    "Tom Clancy's Rainbow Six: Vegas": { hasAchievements: false, count: 0 },
    "Tom Clancy's Rainbow Six: Vegas 2": { hasAchievements: false, count: 0 },
    "Tom Clancy's Rainbow Six® Siege X": { hasAchievements: false, count: 0 },
    "Tom Clancy's Splinter Cell": { hasAchievements: false, count: 0 },
    "Tom Clancy's Splinter Cell Blacklist": { hasAchievements: true, count: 28 },
    "Tom Clancy's Splinter Cell: Chaos Theory": { hasAchievements: false, count: 0 },
    "Tom Clancy's Splinter Cell: Conviction": { hasAchievements: false, count: 0 },
    "Tom Clancy's Splinter Cell: Double Agent": { hasAchievements: false, count: 0 },
    "Tom Clancy's The Division": { hasAchievements: true, count: 60 },
    "Tom Clancy's The Division PTS": { hasAchievements: false, count: 0 },
    "Tomb Raider": { hasAchievements: true, count: 50 },
    "Tomb Raider I-III Remastered Starring Lara Croft": { hasAchievements: true, count: 269 },
    "Tomb Raider IV-VI Remastered": { hasAchievements: true, count: 168 },
    "Town of Salem": { hasAchievements: true, count: 361 },
    "Trials Evolution Gold Edition": { hasAchievements: true, count: 25 },
    "Trials Fusion": { hasAchievements: true, count: 51 },
    "Trials Rising": { hasAchievements: true, count: 53 },
    "Ultimate Chicken Horse": { hasAchievements: true, count: 31 },
    "Ultimate Marvel vs. Capcom 3": { hasAchievements: true, count: 47 },
    "Ultra Street Fighter IV": { hasAchievements: true, count: 67 },
    "Umbrella Corps": { hasAchievements: true, count: 41 },
    "UNCHARTED™: Legacy of Thieves Collection": { hasAchievements: true, count: 101 },
    "Undertale": { hasAchievements: false, count: 0 },
    "UNO": { hasAchievements: true, count: 12 },
    "Unravel": { hasAchievements: true, count: 26 },
    "Unravel Two": { hasAchievements: true, count: 28 },
    "Unreal Tournament 2003": { hasAchievements: false, count: 0 },
    "Unreal Tournament 2004: Editor's Choice Edition": { hasAchievements: false, count: 0 },
    "Unreal Tournament 3 (Retail)": { hasAchievements: false, count: 0 },
    "Unreal Tournament III Black": { hasAchievements: true, count: 57 },
    "Until Dawn™": { hasAchievements: true, count: 29 },
    "Unturned": { hasAchievements: true, count: 88 },
    "Valheim": { hasAchievements: false, count: 0 },
    "Vampire Survivors": { hasAchievements: true, count: 228 },
    "Warhammer 40,000: Space Marine": { hasAchievements: false, count: 0 },
    "Watch Dogs: Legion": { hasAchievements: true, count: 49 },
    "Watch_Dogs": { hasAchievements: true, count: 49 },
    "Watch_Dogs 2": { hasAchievements: true, count: 55 },
    "What Remains of Edith Finch": { hasAchievements: true, count: 9 },
    "Worms": { hasAchievements: false, count: 0 },
    "Worms Pinball": { hasAchievements: false, count: 0 },
    "Yooka-Laylee": { hasAchievements: true, count: 35 },
    "Yooka-Laylee and the Impossible Lair": { hasAchievements: true, count: 47 }
};

// Helper function to get achievement data for a game
function getAchievementData(gameName) {
    // Try exact match first
    if (steamAchievements[gameName]) {
        return steamAchievements[gameName];
    }

    // Try some common name variations
    const variations = [
        gameName.replace(/™/g, '').replace(/®/g, '').trim(),
        gameName.replace(/ \(\d{4}\)/g, ''), // Remove year
        gameName.replace(/: Enhanced Edition|: Definitive Edition|: GOTY/g, ''),
        gameName.replace(/Call of Duty®?:? ?/g, 'Call of Duty: '),
        gameName.replace(/Grand Theft Auto V Legacy/g, 'Grand Theft Auto V'),
        gameName.replace(/Alan Wake's/g, 'Alan Wakes') // Handle apostrophe variations
    ];

    for (const variation of variations) {
        if (steamAchievements[variation]) {
            return steamAchievements[variation];
        }
    }

    // Return default (no achievement data available)
    return { hasAchievements: false, count: 0, unknown: true };
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { steamAchievements, getAchievementData };
}