// How Long To Beat game times - Main Story completion times
const hltbGameTimes = {
    "60 Parsecs!": 2.5,
    "60 Seconds! Reatomized": 6.5,
    "7 Days to Die": 146,
    "A Story About My Uncle": 3.5,
    "A Way Out": 6.5,
    "Adventure Time: Pirates of the Enchiridion": 9.5,
    "Alan Wake": 13,
    "Alan Wake's American Nightmare": 4.5,
    "Alice: Madness Returns": 15.5,
    "Alien: Isolation": 21,
    "American Truck Simulator": 69,
    "Amnesia: The Dark Descent": 8.5,
    "Among Us": 14,
    "Apex Legends": 105,
    "ARK: Survival Evolved": 203,
    "ARK: Survival of the Fittest": 54,
    "ARMA 3": 32,
    "Assassin's Creed": 18,
    "Assassin's Creed: Brotherhood": 24.5,
    "Assassin's Creed Chronicles: China": 8,
    "Assassin's Creed Chronicles: India": 6.5,
    "Assassin's Creed Chronicles: Russia": 7.5,
    "Assassin's Creed: Freedom Cry": 5.5,
    "Assassin's Creed II": 26,
    "Assassin's Creed III": 27,
    "Assassin's Creed III: Remastered": 28,
    "Assassin's Creed IV: Black Flag": 39.5,
    "Assassin's Creed III: Liberation": 11,
    "Assassin's Creed Odyssey": 95,
    "Assassin's Creed Origins": 57,
    "Assassin's Creed: Revelations": 19,
    "Assassin's Creed: Rogue": 20,
    "Assassin's Creed: Syndicate": 34,
    "Assassin's Creed: Unity": 32,
    "Assassin's Creed Valhalla": 105,
    "Batman: Arkham Asylum GOTY Edition": 14.5,
    "Batman: Arkham City GOTY": 20.5,
    "Batman: Arkham Knight": 31,
    "Batman: Arkham Origins": 18.5,
    "BioShock": 12,
    "BioShock 2": 10.5,
    "BioShock Infinite": 11.5,
    "Borderlands 2": 30,
    "Borderlands 3": 23,
    "Call of Duty": 7,
    "Call of Duty 2": 7.5,
    "Call of Duty 4: Modern Warfare (2007)": 7,
    "Call of Duty: Black Ops": 7,
    "Call of Duty: Black Ops II": 7,
    "Call of Duty: Black Ops III": 9,
    "Call of Duty: Modern Warfare 2 (2009)": 6.5,
    "Call of Duty: World at War": 7,
    "Castle Crashers": 5,
    "Celeste": 8,
    "Counter-Strike": 4,
    "Counter-Strike 2": 5,
    "Counter-Strike: Source": 4.5,
    "Cuphead": 11,
    "Cyberpunk 2077": 25,
    "Dead Cells": 15,
    "Dead Rising": 12,
    "Dead Space (2008)": 11,
    "Dead Space 2": 9,
    "Dead Space™ 3": 12,
    "Detroit: Become Human": 12,
    "DOOM": 11,
    "DOOM Eternal": 14,
    "Don't Starve Together": 30,
    "Enter the Gungeon": 15,
    "Fallout": 16,
    "Fallout 2": 18,
    "Fallout 3 - Game of the Year Edition": 22.5,
    "Fallout 4": 27,
    "Fallout: New Vegas": 27.5,
    "Far Cry": 14,
    "Far Cry 2": 16,
    "Far Cry® 3": 15.5,
    "Far Cry 4": 18,
    "Far Cry 5": 18,
    "Far Cry 6": 16.5,
    "Five Nights at Freddy's": 1,
    "Five Nights at Freddy's 2": 1,
    "Five Nights at Freddy's 3": 1,
    "For Honor": 6.5,
    "Garry's Mod": 8,
    "God of War": 20,
    "Golf With Your Friends": 2,
    "Grand Theft Auto III": 15,
    "Grand Theft Auto V Legacy": 31.5,
    "Grand Theft Auto V Enhanced": 31.5,
    "Grand Theft Auto: San Andreas": 31,
    "Grand Theft Auto: Vice City": 19.5,
    "Hades": 22,
    "Half-Life": 12,
    "Half-Life 2": 13,
    "Heavy Rain": 10,
    "Hitman: Absolution": 12.5,
    "Hollow Knight": 27,
    "Horizon Zero Dawn™ Complete Edition": 22.5,
    "INSIDE": 4,
    "It Takes Two": 14,
    "Just Cause": 15,
    "Just Cause 2": 18,
    "Just Cause 3": 15,
    "Kingdom Come: Deliverance": 41,
    "Left 4 Dead 2": 10,
    "LEGO® Batman™: The Videogame": 8,
    "LEGO® Star Wars™: The Complete Saga": 12.5,
    "Life is Strange™": 14,
    "Life is Strange 2": 16,
    "Life is Strange: Before the Storm": 8,
    "LIMBO": 4,
    "Little Nightmares": 4,
    "Little Nightmares II": 5,
    "Mad Max": 19.5,
    "Marvel's Spider-Man Remastered": 17,
    "Mass Effect™ Legendary Edition": 85,
    "Metro 2033": 10,
    "Metro: Last Light Redux": 11,
    "Metro Exodus": 15,
    "No Man's Sky": 30,
    "Ori and the Blind Forest": 8,
    "Ori and the Will of the Wisps": 11,
    "Outlast": 5,
    "Outlast 2": 7,
    "PC Building Simulator": 8,
    "Portal": 3,
    "Portal 2": 8,
    "PowerWash Simulator": 15,
    "Red Dead Redemption 2": 60,
    "Resident Evil 2": 8,
    "Resident Evil 3": 6,
    "Resident Evil 4 (2005)": 16,
    "Resident Evil 7 Biohazard": 9,
    "Resident Evil Village": 10,
    "Rust": 30,
    "Sid Meier's Civilization VI": 60,
    "Stardew Valley": 52.5,
    "STAR WARS Jedi: Fallen Order™": 17,
    "STAR WARS Jedi: Survivor™": 25,
    "Subnautica": 29,
    "Subnautica: Below Zero": 20,
    "Super Meat Boy": 5,
    "Team Fortress 2": 4,
    "Terraria": 51,
    "The Binding of Isaac: Rebirth": 11,
    "The Elder Scrolls V: Skyrim Special Edition": 34,
    "The Forest": 15,
    "The Last of Us™ Part I": 15,
    "The Quarry": 10,
    "The Walking Dead": 12,
    "The Walking Dead: Season Two": 11,
    "The Walking Dead: The Final Season": 12,
    "The Witcher 2: Assassins of Kings Enhanced Edition": 24,
    "The Witcher 3: Wild Hunt": 51.5,
    "The Witcher: Enhanced Edition": 36,
    "Titanfall® 2": 6,
    "Undertale": 7,
    "Until Dawn™": 9,
    "Watch Dogs: Legion": 18,
    "Watch_Dogs": 18,
    "Watch_Dogs 2": 19,
    "What Remains of Edith Finch": 2,
    "XCOM 2": 33
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { hltbGameTimes };
} else {
    window.hltbGameTimes = hltbGameTimes;
}

// HLTB main story times restored