const manualGameTimes = {
    // All completion times cleared - ready for manual entry
};

// Release dates (A-Z alphabetical order)
const releaseDates = {
    // Batch 1 (games 1-20)
    "60 Parsecs!": 2018,
    "60 Seconds! Reatomized": 2019,
    "7 Days to Die": 2013,
    "A Way Out": 2018,
    "Adventure Time: Pirates of the Enchiridion": 2018,
    "Alan Wake": 2010,
    "Alan Wake's American Nightmare": 2012,
    "Alice: Madness Returns": 2011,
    "Alien: Isolation": 2014,
    "American Truck Simulator": 2016,
    "Among Us": 2018,
    "Amnesia: The Dark Descent": 2010,
    "Apex Legends": 2019,
    "ARK: Survival Evolved": 2015,
    "ARK: Survival Of The Fittest": 2016,
    "Arma 3": 2013,
    "Assassin's Creed": 2007,
    "Assassin's Creed II": 2009,
    "Assassin's Creed Brotherhood": 2010,
    "Assassin's Creed III Remastered": 2019,

    // Batch 2 (games 21-40)
    "Assassin's Creed IV Black Flag": 2013,
    "Assassin's Creed Freedom Cry": 2013,
    "Assassin's Creed Liberation": 2012,
    "Assassin's Creed Odyssey": 2018,
    "Assassin's Creed Origins": 2017,
    "Assassin's Creed Revelations": 2011,
    "Assassin's Creed Rogue": 2014,
    "Assassin's Creed Syndicate": 2015,
    "Assassin's Creed Unity": 2014,
    "Assassin's Creed Valhalla": 2020,
    "Assassin's Creed® Chronicles: China": 2015,
    "Assassin's Creed® Chronicles: India": 2016,
    "Assassin's Creed® Chronicles: Russia": 2016,
    "Assassin's Creed® III": 2012,
    "Back 4 Blood": 2021,
    "Batman - The Telltale Series": 2016,
    "Batman: Arkham Asylum GOTY Edition": 2009,
    "Batman: Arkham City GOTY": 2011,
    "Batman: The Enemy Within - The Telltale Series": 2017,
    "Batman™: Arkham Knight": 2015,
    "BattleBlock Theater": 2013,

    // Batch 3 (games 41-60)
    "Batman™: Arkham Origins": 2013,
    "Batman™: Arkham Origins Blackgate - Deluxe Edition": 2014,
    "BattleBit Remastered": 2023,
    "Battlefield 3™": 2011,
    "Battlefield 4™": 2013,
    "Battlefield™ 1": 2016,
    "Battlefield™ 2042": 2021,
    "Battlefield™ Hardline": 2015,
    "Battlefield™ V": 2018,
    "BioShock": 2007,
    "BioShock 2": 2010,
    "BioShock 2 Remastered": 2016,
    "BioShock Infinite": 2013,
    "BioShock Remastered": 2016,
    "Black Desert": 2014,
    "Blood and Bacon": 2013,
    "Bloons TD 6": 2018,
    "Borderlands 2": 2012,
    "Borderlands 3": 2019,

    // Batch 4 (games 61-80)
    "Borderlands: The Pre-Sequel": 2014,
    "Borderlands GOTY": 2009,
    "Borderlands GOTY Enhanced": 2019,
    "Brotato": 2022,
    "Bully: Scholarship Edition": 2008,
    "Burnout™ Paradise Remastered": 2018,
    "Call of Duty (2003)": 2003,
    "Call of Duty 2": 2005,
    "Call of Duty 4: Modern Warfare (2007)": 2007,
    "Call of Duty: Advanced Warfare": 2014,
    "Call of Duty: Advanced Warfare - Multiplayer": 2014,
    "Call of Duty: Black Ops": 2010,
    "Call of Duty: Black Ops - Multiplayer": 2010,
    "Call of Duty: Black Ops II": 2012,
    "Call of Duty: Black Ops II - Multiplayer": 2012,
    "Call of Duty: Black Ops II - Zombies": 2012,
    "Call of Duty: Black Ops III": 2015,
    "Call of Duty®: Black Ops Cold War": 2020,
    "Call of Duty: Ghosts": 2013,

    // Batch 5 (games 81-100)
    "Call of Duty: Ghosts - Multiplayer": 2013,
    "Call of Duty: Infinite Warfare": 2016,
    "Call of Duty: Modern Warfare 2 (2009)": 2009,
    "Call of Duty: Modern Warfare 2 (2009) - Multiplayer": 2009,
    "Call of Duty: Modern Warfare Remastered (2017)": 2016,
    "Call of Duty: Modern Warfare Remastered - Multiplayer": 2016,
    "Call of Duty®": 2019,
    "Call of Duty®: Modern Warfare®": 2019,
    "Call of Duty®: Modern Warfare® II": 2022,
    "Call of Duty®: Modern Warfare® II - Open Beta": 2022,
    "Call of Duty®: Modern Warfare® 3 (2011)": 2011,
    "Call of Duty®: Modern Warfare® 3 (2011) - Multiplayer": 2011,
    "Call of Duty®: Modern Warfare® III": 2023,
    "Call of Duty: United Offensive": 2004,
    "Call of Duty®: Vanguard": 2021,
    "Call of Duty: World at War": 2008,
    "Call of Duty: WWII": 2017,
    "Call of Duty: WWII - Multiplayer": 2017,
    "Capcom Fighting Collection": 2022,
    "Castle Crashers": 2008,

    // Batch 6 (games 101-140)
    "Celeste": 2018,
    "Chained Together": 2024,
    "Clustertruck": 2016,
    "Comedy Night": 2017,
    "Content Warning": 2024,
    "Contra Anniversary Collection": 2019,
    "Control Ultimate Edition": 2019,
    "Cookie Clicker": 2013,
    "Counter-Strike": 2000,
    "Counter-Strike 2": 2023,
    "Counter-Strike: Condition Zero": 2004,
    "Counter-Strike: Condition Zero Deleted Scenes": 2004,
    "Counter-Strike: Source": 2004,
    "Crab Game": 2021,
    "Crash Bandicoot™ N. Sane Trilogy": 2017,
    "Crusader Kings II": 2012,
    "Cult of the Lamb": 2022,
    "Cuphead": 2017,
    "Cyberpunk 2077": 2020,
    "Darkest Dungeon®": 2016,
    "Days Gone": 2019,
    "DayZ": 2013,
    "Dead by Daylight": 2016,
    "Dead Cells": 2017,
    "Dead Island Definitive Edition": 2016,
    "Dead Island Retro Revenge": 2016,
    "Dead Island Riptide Definitive Edition": 2016,
    "Dead Rising": 2006,
    "Dead Rising 2": 2010,
    "Dead Rising 2: Off the Record": 2011,
    "Dead Rising 3": 2013,
    "Dead Rising 4": 2016,
    "Dead Space (2008)": 2008,
    "Dead Space 2": 2011,
    "Dead Space™ 3": 2013,
    "Deceit": 2017,

    // Batch 7 (games 141-180)
    "Deep Rock Galactic": 2018,
    "Destroy All Humans!": 2020,
    "Detroit: Become Human": 2018,
    "Deus Ex: Game of the Year Edition": 2000,
    "Deus Ex: Human Revolution - Director's Cut": 2011,
    "Deus Ex: Invisible War": 2003,
    "Deus Ex: Mankind Divided™": 2016,
    "Deus Ex: The Fall": 2013,
    "Devolverland Expo": 2020,
    "Dishonored": 2012,
    "Dishonored 2": 2016,
    "Don't Starve": 2013,
    "Don't Starve Together": 2016,
    "Donut County": 2018,
    "DOOM": 2016,
    "DOOM + DOOM II": 2019,
    "DOOM 3": 2004,
    "DOOM 3: BFG Edition": 2012,
    "DOOM 3: Resurrection of Evil": 2005,
    "DOOM 64": 2020,
    "DOOM Eternal": 2020,
    "DOOM II": 1994,
    "Drug Dealer Simulator": 2020,
    "Due Process": 2020,
    "Dungeon Defenders": 2011,
    "Dungeon Defenders II": 2015,
    "Dying Light": 2015,
    "Dying Light 2: Reloaded Edition": 2022,
    "Enter the Gungeon": 2016,
    "Escape Dead Island": 2014,
    "Escape Memoirs: Mini Stories": 2021,
    "Escape the Backrooms": 2022,
    "Euro Truck Simulator 2": 2012,
    "Exit the Gungeon": 2020,
    "Fable Anniversary": 2014,
    "Fall Guys": 2020,
    "Fallout": 1997,
    "Fallout 2": 1998,
    "Fallout 3 - Game of the Year Edition": 2008,
    "Fallout 4": 2015,

    // Batch 8 (games 181-220)
    "Fallout 76": 2018,
    "Fallout: New Vegas": 2010,
    "Fallout Shelter": 2015,
    "Fallout Tactics": 2001,
    "Far Cry": 2004,
    "Far Cry 2": 2008,
    "Far Cry 4": 2014,
    "Far Cry 5": 2018,
    "Far Cry 6": 2021,
    "Far Cry New Dawn": 2019,
    "Far Cry Primal": 2016,
    "Far Cry® 3": 2012,
    "Far Cry® 3 Blood Dragon": 2013,
    "Fears to Fathom - Carson House": 2023,
    "Fears to Fathom - Home Alone": 2021,
    "Fears to Fathom - Ironbark Lookout": 2023,
    "Fears to Fathom - Norwood Hitchhike": 2022,
    "Fears to Fathom - Woodbury Getaway": 2024,
    "Final DOOM": 1996,
    "FINAL FANTASY": 1987,
    "FINAL FANTASY II": 1988,
    "FINAL FANTASY III": 1990,
    "FINAL FANTASY IV": 1991,
    "FINAL FANTASY TYPE-0 HD": 2015,
    "FINAL FANTASY V": 1992,
    "FINAL FANTASY VI": 1994,
    "FINAL FANTASY VII": 1997,
    "FINAL FANTASY IX": 2000,
    "FINAL FANTASY XII THE ZODIAC AGE": 2017,
    "FINAL FANTASY XIII": 2009,
    "FINAL FANTASY XIII-2": 2011,
    "FINAL FANTASY XV WINDOWS EDITION": 2018,
    "Firewatch": 2016,
    "Five Nights at Freddy's": 2014,
    "Five Nights at Freddy's 2": 2014,
    "Five Nights at Freddy's 3": 2015,
    "For Honor": 2017,
    "The Forest": 2014,
    "Friday the 13th: The Game": 2017,
    "Gang Beasts": 2017,
    "Garfield Kart": 2013,
    "Garfield Kart - Furious Racing": 2019,

    // Batch 9 (games 221-304) - 84 games
    "Garry's Mod": 2006,
    "Genital Jousting": 2016,
    "Geometry Dash": 2013,
    "Getting Over It with Bennett Foddy": 2017,
    "Goat Simulator": 2014,
    "God of War": 2018,
    "Golf It!": 2017,
    "Golf With Your Friends": 2020,
    "Goose Goose Duck": 2021,
    "Grand Theft Auto III": 2001,
    "Grand Theft Auto III - The Definitive Edition": 2021,
    "Grand Theft Auto IV: The Complete Edition": 2008,
    "Grand Theft Auto V Enhanced": 2014,
    "Grand Theft Auto V Legacy": 2013,
    "Grand Theft Auto: San Andreas": 2004,
    "Grand Theft Auto: San Andreas - The Definitive Edition": 2021,
    "Grand Theft Auto: Vice City": 2002,
    "Grand Theft Auto: Vice City - The Definitive Edition": 2021,
    "Graveyard Keeper": 2018,
    "GRIS": 2018,
    "Grounded": 2020,
    "Grow Home": 2015,
    "Grow Up": 2016,
    "GTFO": 2019,
    "Hades": 2020,
    "Half-Life": 1998,
    "Half-Life 2": 2004,
    "Half-Life 2: Deathmatch": 2004,
    "Half-Life Deathmatch: Source": 2005,
    "Half-Life: Blue Shift": 2001,
    "Half-Life: Opposing Force": 1999,
    "Half-Life: Source": 2004,
    "Halo Infinite": 2021,
    "Halo Wars: Definitive Edition": 2017,
    "Halo: Spartan Assault": 2013,
    "Halo: Spartan Strike": 2015,
    "Halo: The Master Chief Collection": 2014,
    "Hand Simulator": 2019,
    "Hand Simulator: Survival": 2020,
    "Heavy Rain": 2010,
    "Hellblade: Senua's Sacrifice": 2017,
    "Hellblade: Senua's Sacrifice VR Edition": 2018,
    "HELLDIVERS™": 2015,
    "HELLDIVERS™ 2": 2024,
    "Hello Neighbor": 2017,
    "Hitman: Absolution": 2012,
    "Hitman: Blood Money": 2006,
    "Hitman: Codename 47": 2000,
    "Hitman: Contracts": 2004,
    "Hitman 2: Silent Assassin": 2002,
    "Hitman GO: Definitive Edition": 2016,
    "HITMAN™": 2016,
    "HITMAN™ 2": 2018,
    "HITMAN World of Assassination": 2023,
    "Hitman: Sniper Challenge": 2012,
    "Hogwarts Legacy": 2023,
    "Hollow Knight": 2017,
    "Hollow Knight: Silksong": 2023,
    "Horizon Zero Dawn™ Complete Edition": 2017,
    "Hotline Miami": 2012,
    "Hotline Miami 2: Wrong Number": 2015,
    "House Flipper": 2018,
    "House Party": 2017,
    "Human Fall Flat": 2016,
    "I Am Bread": 2015,
    "In Silence": 2020,
    "Injustice: Gods Among Us Ultimate Edition": 2013,
    "Injustice™ 2": 2017,
    "INSIDE": 2016,
    "It Takes Two": 2021,
    "Just Cause": 2006,
    "Just Cause 2": 2010,
    "Just Cause 3": 2015,
    "Just Cause 4": 2018,
    "Keep Talking and Nobody Explodes": 2015,
    "Killing Floor": 2009,
    "Killing Floor 2": 2016,
    "Kingdom Come: Deliverance": 2018,
    "Lara Croft and the Guardian of Light": 2010,
    "Lara Croft and the Temple of Osiris": 2014,
    "Lara Croft GO": 2015,
    "Left 4 Dead": 2008,
    "Left 4 Dead 2": 2009,

    // Batch 10 (games 305-389) - 85 games
    "LEGO® Batman™ 2: DC Super Heroes": 2012,
    "LEGO® Batman™ 3: Beyond Gotham": 2014,
    "LEGO® Batman™: The Videogame": 2008,
    "LEGO® Builder's Journey": 2019,
    "LEGO® City Undercover": 2017,
    "LEGO® DC Super-Villains": 2018,
    "LEGO® Harry Potter: Years 1-4": 2010,
    "LEGO® Harry Potter: Years 5-7": 2011,
    "LEGO® Harry Potter™ Collection": 2016,
    "LEGO® Indiana Jones™ 2: The Adventure Continues": 2009,
    "LEGOⓇ Indiana Jones™: The Original Adventures": 2008,
    "LEGO® Jurassic World": 2015,
    "LEGO® MARVEL Super Heroes": 2013,
    "LEGO® MARVEL Super Heroes 2": 2017,
    "LEGO® MARVEL's Avengers": 2016,
    "LEGO® Pirates of the Caribbean The Video Game": 2011,
    "LEGO® Star Wars™ III: The Clone Wars™": 2011,
    "LEGO® STAR WARS™: The Force Awakens": 2016,
    "LEGO® Star Wars™: The Complete Saga": 2007,
    "LEGO® Star Wars™: The Skywalker Saga": 2022,
    "LEGO® The Hobbit™": 2014,
    "LEGO® The Incredibles": 2018,
    "LEGO® The LEGO® Movie - Videogame": 2014,
    "LEGO® The LEGO® Movie 2 - Videogame": 2019,
    "LEGO® The Lord of the Rings™": 2012,
    "LEGO® The LEGO® NINJAGO® Movie Video Game": 2017,
    "LEGO® Worlds": 2017,
    "Lethal Company": 2023,
    "Life is Strange 2": 2018,
    "Life is Strange: Before the Storm": 2017,
    "Life is Strange: Before the Storm Remastered": 2022,
    "Life is Strange Remastered": 2021,
    "Life is Strange™": 2015,
    "Life is Strange: True Colors": 2021,
    "LIGHTNING RETURNS: FINAL FANTASY XIII": 2013,
    "LIMBO": 2010,
    "Little Nightmares": 2017,
    "Little Nightmares Enhanced Edition": 2017,
    "Little Nightmares II": 2021,
    "LOCKDOWN Protocol": 2023,
    "Longvinter": 2021,
    "Mad Max": 2015,
    "Mage Arena": 2020,
    "Mafia": 2002,
    "Mafia II (Classic)": 2010,
    "Mafia II: Definitive Edition": 2020,
    "Mafia III: Definitive Edition": 2020,
    "Mafia: Definitive Edition": 2020,
    "Marvel Rivals": 2024,
    "Marvel vs. Capcom: Infinite": 2017,
    "Marvel's Avengers - The Definitive Edition": 2020,
    "Marvel's Guardians of the Galaxy": 2021,
    "Marvel's Spider-Man: Miles Morales": 2020,
    "Marvel's Spider-Man Remastered": 2018,
    "Mass Effect™ Legendary Edition": 2021,
    "Master Levels for DOOM II": 1995,
    "Max Payne": 2001,
    "Max Payne 2: The Fall of Max Payne": 2003,
    "Max Payne 3": 2012,
    "Metro 2033": 2010,
    "Metro 2033 Redux": 2014,
    "Metro Exodus": 2019,
    "Metro Exodus Enhanced Edition": 2021,
    "Metro: Last Light Complete Edition": 2013,
    "Metro: Last Light Redux": 2014,
    "MiniRoyale": 2021,
    "Mirror's Edge": 2008,
    "Mirror's Edge™ Catalyst": 2016,
    "Monopoly Plus": 2014,
    "Moonlighter": 2018,
    "Mortal Kombat 11": 2019,
    "Mortal Kombat X": 2015,
    "MultiVersus": 2022,
    "My Friend Pedro": 2019,
    "NBA 2K24": 2023,
    "Need for Speed™": 2015,
    "Need for Speed™ Heat": 2019,
    "Need for Speed™ Hot Pursuit Remastered": 2020,
    "Need for Speed™ Most Wanted": 2012,
    "Need for Speed™ Payback": 2017,
    "Need for Speed™ Rivals": 2013,
    "Need for Speed™ Unbound": 2022,
    "Never Alone (Kisima Ingitchuna)": 2014,
    "New Tales from the Borderlands": 2022,
    "No Man's Sky": 2016,

    // Batch 11 (games 390-571) - 182 games
    "Ori and the Blind Forest": 2015,
    "Ori and the Blind Forest: Definitive Edition": 2016,
    "Ori and the Will of the Wisps": 2020,
    "Outlast": 2013,
    "Outlast 2": 2017,
    "Overcooked": 2016,
    "Overcooked! 2": 2018,
    "Overwatch® 2": 2022,
    "Pacify": 2019,
    "Palworld": 2024,
    "PAYDAY 2": 2013,
    "PC Building Simulator": 2018,
    "PEAK": 2021,
    "Phasmophobia": 2020,
    "PICO PARK": 2021,
    "Planet Coaster": 2016,
    "Plants vs. Zombies: Battle for Neighborville": 2019,
    "Plants vs. Zombies: Game of the Year": 2009,
    "Plants vs. Zombies™ Garden Warfare 2: Deluxe Edition": 2016,
    "Portal": 2007,
    "Portal 2": 2011,
    "Portal 2 - The Final Hours": 2011,
    "Portal with RTX": 2022,
    "PowerWash Simulator": 2021,
    "Prince of Persia": 2008,
    "Prince of Persia: The Forgotten Sands": 2010,
    "Prince of Persia: The Sands of Time": 2003,
    "Prince of Persia: The Two Thrones": 2005,
    "Prince of Persia: Warrior Within": 2004,
    "Prototype": 2009,
    "PROTOTYPE 2": 2012,
    "PUBG: BATTLEGROUNDS": 2017,
    "Punch Club": 2016,
    "Quake Champions": 2017,
    "The Quarry": 2022,
    "RAGE": 2011,
    "RAGE 2": 2019,
    "Raft": 2018,
    "Rayman Legends": 2013,
    "Rayman Origins": 2011,
    "Rayman: Raving Rabbids": 2006,
    "Rec Room": 2016,
    "Red Dead Redemption": 2010,
    "Red Dead Redemption 2": 2018,
    "Resident Evil": 2015,
    "Resident Evil 0": 2016,
    "Resident Evil 2": 2019,
    "Resident Evil 3": 2020,
    "Resident Evil 4 (2005)": 2005,
    "Resident Evil 5": 2009,
    "Resident Evil 6": 2012,
    "Resident Evil 7 Biohazard": 2017,
    "Resident Evil Re:Verse": 2022,
    "RESIDENT EVIL RESISTANCE": 2020,
    "Resident Evil Revelations": 2012,
    "Resident Evil Revelations 2": 2015,
    "Resident Evil Village": 2021,
    "Return to Castle Wolfenstein": 2001,
    "Rise of the Tomb Raider": 2015,
    "Risk of Rain (2013)": 2013,
    "Rust": 2013,
    "Rust - Staging Branch": 2013,
    "Saints Row 2": 2008,
    "Saints Row IV": 2013,
    "Saints Row: Gat out of Hell": 2015,
    "Saints Row: The Third": 2011,
    "Saints Row The Third Remastered": 2020,
    "Scooby-Doo! & Looney Tunes Cartoon Universe: Adventure": 2021,
    "Scott Pilgrim vs The World": 2020,
    "Scribblenauts Unlimited": 2012,
    "Scribblenauts Unmasked": 2013,
    "Sea of Thieves": 2018,
    "SEGA Mega Drive & Genesis Classics": 2018,
    "Shadow of the Tomb Raider": 2018,
    "Shower With Your Dad Simulator 2015: Do You Still Shower With Your Dad": 2015,
    "Sid Meier's Civilization VI": 2016,
    "Slay the Spire": 2017,
    "Slime Rancher": 2017,
    "Slime Rancher 2": 2022,
    "Sniper Elite": 2005,
    "Sniper Elite 3": 2014,
    "Sniper Elite 4": 2017,
    "Sniper Elite 5": 2022,
    "Sniper Elite V2": 2012,
    "Sniper Elite V2 Remastered": 2019,
    "Sonic & All-Stars Racing Transformed Collection": 2012,
    "Sonic Adventure DX": 2003,
    "Sonic Adventure™ 2": 2001,
    "Sonic and SEGA All Stars Racing": 2010,
    "Sonic CD": 2011,
    "Sonic Forces": 2017,
    "Sonic Generations": 2011,
    "Sonic Lost World": 2013,
    "Sonic Mania": 2017,
    "SONIC THE HEDGEHOG 4 Episode I": 2010,
    "SONIC THE HEDGEHOG 4 Episode II": 2012,
    "South Park The Fractured But Whole": 2017,
    "South Park™: The Stick of Truth™": 2014,
    "SpeedRunners": 2013,
    "Split Fiction": 2024,
    "Splitgate": 2021,
    "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated": 2020,
    "Spore": 2008,
    "Spyro™ Reignited Trilogy": 2018,
    "Starbound": 2016,
    "Stardew Valley": 2016,
    "STAR WARS Jedi: Fallen Order™": 2019,
    "STAR WARS Jedi: Survivor™": 2023,
    "STAR WARS™ Battlefront™": 2015,
    "STAR WARS™ Battlefront™ II": 2017,
    "STAR WARS™: Squadrons": 2020,
    "Stick Fight: The Game": 2017,
    "Street Fighter 30th Anniversary Collection": 2018,
    "Street Fighter V": 2016,
    "Subnautica": 2014,
    "Subnautica: Below Zero": 2021,
    "Suicide Squad: Kill the Justice League": 2024,
    "Sunset Overdrive": 2014,
    "Super Meat Boy": 2010,
    "Surgeon Simulator": 2013,
    "Tales from the Borderlands": 2014,
    "Team Fortress 2": 2007,
    "Team Fortress Classic": 1999,
    "Team Sonic Racing™": 2019,
    "Terraria": 2011,
    "The Awesome Adventures of Captain Spirit": 2018,
    "The Binding of Isaac: Rebirth": 2014,
    "The Crew 2": 2018,
    "The Elder Scrolls III: Morrowind": 2002,
    "The Elder Scrolls IV: Oblivion Game of the Year Edition (2009)": 2006,
    "The Elder Scrolls V: Skyrim Special Edition": 2016,
    "The Evil Within": 2014,
    "The Evil Within 2": 2017,
    "THE GAME OF LIFE": 2016,
    "The Lab": 2016,
    "The Last of Us™ Part I": 2022,
    "The LEGO® Movie - Videogame": 2014,
    "The LEGO® Movie 2 - Videogame": 2019,
    "The LEGO® NINJAGO® Movie Video Game": 2017,
    "The Outer Worlds: Spacer's Choice Edition": 2019,
    "The Sims™ 4": 2014,
    "The Walking Dead": 2012,
    "The Walking Dead: A New Frontier": 2016,
    "The Walking Dead: Michonne": 2016,
    "The Walking Dead: Season Two": 2013,
    "The Walking Dead: The Final Season": 2018,
    "The Walking Dead: The Telltale Definitive Series": 2019,
    "The Witcher 2: Assassins of Kings Enhanced Edition": 2012,
    "The Witcher 3: Wild Hunt": 2015,
    "The Witcher: Enhanced Edition": 2008,
    "The Wolf Among Us": 2013,
    "theHunter: Call of the Wild™": 2017,
    "Thief": 2014,
    "Thief Gold": 1998,
    "Thief: Deadly Shadows": 2004,
    "Thief™ II: The Metal Age": 2000,
    "Tiny Tina's Wonderlands": 2022,
    "Titanfall® 2": 2016,
    "Tom Clancy's EndWar": 2008,
    "Tom Clancy's Ghost Recon": 2001,
    "Tom Clancy's Ghost Recon: Desert Siege": 2002,
    "Tom Clancy's Ghost Recon Future Soldier": 2012,
    "Tom Clancy's Ghost Recon: Island Thunder": 2002,
    "Tom Clancy's Ghost Recon® Wildlands": 2017,
    "Tom Clancy's Rainbow Six 3: Athena Sword": 2004,
    "Tom Clancy's Rainbow Six 3: Gold Edition": 2003,
    "Tom Clancy's Rainbow Six: Lockdown": 2005,
    "Tom Clancy's Rainbow Six® Siege X": 2015,
    "Tom Clancy's Rainbow Six: Vegas": 2006,
    "Tom Clancy's Rainbow Six: Vegas 2": 2008,
    "Tom Clancy's Splinter Cell": 2002,
    "Tom Clancy's Splinter Cell Blacklist": 2013,
    "Tom Clancy's Splinter Cell: Chaos Theory": 2005,
    "Tom Clancy's Splinter Cell: Conviction": 2010,
    "Tom Clancy's Splinter Cell: Double Agent": 2006,
    "Tom Clancy's The Division": 2016,

    // 🏁 FINAL BATCH (games 572-628) - 57 games - MISSION COMPLETE! 🏁
    "Tomb Raider": 2013,
    "Tomb Raider I": 1996,
    "Tomb Raider II": 1997,
    "Tomb Raider III: Adventures of Lara Croft": 1998,
    "Tomb Raider: Anniversary": 2007,
    "Tomb Raider: Chronicles (2000)": 2000,
    "Tomb Raider (VI): The Angel of Darkness (2003)": 2003,
    "Tomb Raider I-III Remastered Starring Lara Croft": 2024,
    "Tomb Raider: Legend": 2006,
    "Tomb Raider: The Last Revelation (1999)": 1999,
    "Tomb Raider: Underworld": 2008,
    "Town of Salem": 2014,
    "Trials Evolution Gold Edition": 2012,
    "Trials Fusion": 2014,
    "Trials Rising": 2019,
    "Ultimate Chicken Horse": 2016,
    "Ultimate Marvel vs. Capcom 3": 2011,
    "Ultra Street Fighter IV": 2014,
    "Umbrella Corps": 2016,
    "UNCHARTED™: Legacy of Thieves Collection": 2022,
    "Undertale": 2015,
    "UNO": 2016,
    "Unravel": 2016,
    "Unravel Two": 2018,
    "Until Dawn™": 2015,
    "Unturned": 2014,
    "Wallpaper Engine": 2016,
    "Watch Dogs: Legion": 2020,
    "Watch_Dogs": 2014,
    "Watch_Dogs 2": 2016,
    "Welcome to the Game": 2016,
    "What Remains of Edith Finch": 2017,
    "Witch It": 2020,
    "Wizard of Legend": 2018,
    "Wizard101": 2008,
    "Wolfenstein 3D": 1992,
    "Wolfenstein 3D: Spear of Destiny": 1992,
    "Wolfenstein: Enemy Territory": 2003,
    "Wolfenstein II: The New Colossus": 2017,
    "Wolfenstein: The New Order": 2014,
    "Wolfenstein: The Old Blood": 2015,
    "Wolfenstein: Youngblood": 2019,
    "Worms": 1995,
    "Worms Armageddon": 1999,
    "Worms Blast": 2002,
    "Worms Clan Wars": 2013,
    "Worms Crazy Golf": 2011,
    "Worms Pinball": 2007,
    "Worms Reloaded": 2010,
    "Worms Revolution": 2012,
    "Worms Rumble": 2020,
    "Worms Ultimate Mayhem": 2011,
    "Worms W.M.D": 2016,
    "Worms World Party Remastered": 2015,
    "XCOM 2": 2016,
    "Youtubers Life": 2016,
    "Death Stranding Directors Cut": 2022,
    "Escape Simulator": 2021,
    "Five Nights at Freddy's 4": 2015,
    "Five Nights at Freddy's: Sister Location": 2016,
    "Flight Simulator X Steam Edition": 2014,
    "Frostpunk": 2018,
    "Tomb Raider IV-VI Remastered": 2025,
    "Company of Heroes 2": 2013,
    "Dead Space": 2023,
    "DEATHLOOP": 2021,
    "Destroy All Humans! 2 - Reprobed": 2022,
    "High on Life": 2022,
    "Prey": 2017,
    "Pummel Party": 2018,
    "R.E.P.O": 2025,
    "Saints Row": 2023,
    "Sleeping Dogs: Definitive Edition": 2014,
    "SOMA": 2015,
    "SpongeBob SquarePants: The Cosmic Shake": 2023,
    "SOUTH PARK: SNOW DAY!": 2024,
    "The Elder Scrolls® Online": 2014,
    "Yooka-Laylee": 2017,
    "Yooka-Laylee and the Impossible Lair": 2019,

    // New games (true original release year, not Steam listing date -
    // several of these are re-releases/ports where Steam's own
    // release_date field reflects when the *listing* went up, not the
    // game's actual release; verified against other sources where the
    // two diverged)
    "Gamble With Your Friends": 2026,
    "Cloverpit": 2025,
    "KEEP GAMBLING": 2025,
    "Within of Static - Ashburg Rental": 2025,
    "TCG Card Shop Simulator": 2024,
    "Fears to Fathom - Scratch Creek": 2026,
    "Within of Static - Northgate Mall": 2026,
    "Tales Beyond The Tomb - No Witnesses": 2026,
    "Tales Beyond The Tomb - Route 86": 2025,
    "Tales Beyond The Tomb - White Silence": 2025,
    "A Game About Digging A Hole": 2025,
    "Riders Republic": 2021,
    "THE GAME OF LIFE 2": 2020,
    "The Texas Chain Saw Massacre": 2023,
    "STAR WARS Battlefront (Classic, 2004)": 2004,
    "Planet Zoo": 2019,
    "Who's Your Daddy?!": 2016,
    "Black Mesa": 2020,
    "POSTAL 2": 2003,
    "The Binding of Isaac": 2011,
    "Dragon Age: Origins - Ultimate Edition": 2009,
    "FINAL FANTASY VIII": 1999,
    "STAR WARS Knights of the Old Republic": 2003,
    "Fallout 3": 2008,
    "Star Wars: Battlefront 2 (Classic, 2005)": 2005,
    "Tales Beyond The Tomb - The Last Vigil": 2025,
    "Backrooms: Escape Together": 2022,
    "Tales Beyond The Tomb - The Farm's Secret": 2024,
    "Tales Beyond The Tomb - Pineville Night Stalker": 2024,
    "The Stanley Parable: Ultra Deluxe": 2022,
    "Resident Evil (1996)": 1996,
    "Resident Evil 3 Nemesis (1999)": 1999,
    "Resident Evil 2 (1998)": 1998,
    "EA SPORTS Madden NFL 26": 2025,
    "Hellblade II: Senua's Saga": 2024,
    "Sonic Colors: Ultimate": 2021,
    "Mortal Kombat 1": 2023,
    "Sonic Origins": 2022,
    "Gotham Knights": 2022,
    "Hello Neighbor 2": 2022,
    "Overcooked! All You Can Eat": 2020,
    "FINAL FANTASY VIII - REMASTERED": 2019,
    "Dishonored: Death of the Outsider": 2017,
    "State of Decay 2": 2018,
    "FINAL FANTASY IV: THE AFTER YEARS": 2008,
    "State of Decay: Year-One": 2013,
    "Final Fantasy IV (3D Remake)": 2007,
    "The Long Dark": 2017,
    "Final Fantasy III (3D Remake)": 2006,
    "L.A. Noire": 2011,
    "Manhunt": 2003,
    "Balatro": 2024,
    "Tom Clancy's Splinter Cell: Pandora Tomorrow": 2004,
    "Tom Clancy's The Division 2": 2019,
    "F.E.A.R.: Perseus Mandate": 2007,
    "F.E.A.R.: Extraction Point": 2006,
    "F.E.A.R. 3": 2011,
    "F.E.A.R.": 2005,
    "F.E.A.R.2: Project Origin": 2009,
    "Sons Of The Forest": 2024,
    "Dead Island 2": 2023,
    "Risk of Rain 2": 2020,
    "Battlefield 6": 2025
};

// Create the full database with all games
const gameDatabase = {};

// Your full game list
const allGames = [
    "Rust", "LOCKDOWN Protocol", "Counter-Strike 2", "Call of Duty®", "Crab Game",
    "Call of Duty: Black Ops II - Multiplayer", "Stardew Valley", "Terraria", "Wallpaper Engine",
    "Call of Duty: Black Ops III", "The Witcher 3: Wild Hunt", "Marvel Rivals", "Fall Guys",
    "The Witcher: Enhanced Edition", "Call of Duty: Black Ops II - Zombies", "Raft", "Borderlands 2",
    "Call of Duty: Black Ops", "South Park The Fractured But Whole", "MultiVersus",
    "Call of Duty: World at War", "Call of Duty 4: Modern Warfare (2007)", "Call of Duty: Black Ops II",
    "Garry's Mod", "Cyberpunk 2077", "South Park™: The Stick of Truth™", "Among Us", "Deceit",
    "Overwatch® 2", "LEGO® Star Wars™: The Complete Saga", "The Witcher 2: Assassins of Kings Enhanced Edition",
    "Borderlands GOTY", "Slime Rancher", "Assassin's Creed II", "Lethal Company", "Don't Starve Together",
    "Portal 2", "Call of Duty: Modern Warfare 2 (2009)", "Assassin's Creed", "Call of Duty®: Modern Warfare® 3 (2011)",
    "Destroy All Humans!", "Palworld", "The Forest", "Marvel's Spider-Man Remastered", "Mad Max",
    "Dungeon Defenders II", "Castle Crashers", "The Walking Dead", "Life is Strange 2", "Life is Strange™",
    "Cookie Clicker", "PUBG: BATTLEGROUNDS", "Unturned", "Call of Duty®: Modern Warfare® II - Open Beta",
    "Life is Strange: Before the Storm", "It Takes Two", "Blood and Bacon", "Quake Champions",
    "Detroit: Become Human", "The Walking Dead: A New Frontier", "House Party", "The Walking Dead: Season Two",
    "INSIDE", "The Quarry", "Golf With Your Friends", "Far Cry", "Portal", "HELLDIVERS™ 2",
    "A Way Out", "Phasmophobia", "Clustertruck", "Human Fall Flat", "Call of Duty: WWII - Multiplayer",
    "Call of Duty 2", "ARK: Survival Evolved", "LIMBO", "Chained Together", "Assassin's Creed Brotherhood",
    "Hello Neighbor", "Call of Duty (2003)", "Call of Duty: United Offensive", "Grand Theft Auto V Legacy",
    "Apex Legends", "Portal with RTX", "BattleBlock Theater", "STAR WARS Jedi: Fallen Order™",
    "Call of Duty: Infinite Warfare", "Half-Life", "Comedy Night", "Call of Duty: Ghosts", "PEAK",
    "BioShock", "Borderlands GOTY Enhanced", "Tom Clancy's Rainbow Six® Siege X", "Plants vs. Zombies™ Garden Warfare 2: Deluxe Edition",
    "Escape Memoirs: Mini Stories", "LEGO® Batman™: The Videogame", "Shower With Your Dad Simulator 2015: Do You Still Shower With Your Dad",
    "Far Cry 2", "Youtubers Life", "Fallout", "Hogwarts Legacy", "Content Warning", "Spyro™ Reignited Trilogy",
    "Bloons TD 6", "In Silence", "Red Dead Redemption 2", "LEGO® Builder's Journey", "Call of Duty: Ghosts - Multiplayer",
    "Splitgate", "Fallout 4", "Just Cause", "PowerWash Simulator", "Team Fortress 2", "Super Meat Boy",
    "Left 4 Dead 2", "Dungeon Defenders", "Pacify", "NBA 2K24", "Wizard101", "Never Alone (Kisima Ingitchuna)",
    "What Remains of Edith Finch", "MiniRoyale", "The Awesome Adventures of Captain Spirit", "Fallout: New Vegas",
    "Getting Over It with Bennett Foddy", "Bully: Scholarship Edition",
    "Fears to Fathom - Carson House", "Fears to Fathom - Home Alone", "Fears to Fathom - Ironbark Lookout", "Fears to Fathom - Norwood Hitchhike",
    "Fears to Fathom - Woodbury Getaway", "Devolverland Expo", "Donut County", "Until Dawn™", "Escape the Backrooms",
    "UNO", "Mage Arena", "God of War", "Halo: The Master Chief Collection", "Lara Croft GO",
    "Call of Duty: Advanced Warfare - Multiplayer", "Welcome to the Game", "Rec Room", "Tomb Raider: Underworld",
    "Call of Duty: Modern Warfare 2 (2009) - Multiplayer", "Dead by Daylight", "LEGOⓇ Indiana Jones™: The Original Adventures",
    "Tomb Raider I", "60 Seconds! Reatomized", "Hand Simulator: Survival", "The Walking Dead: The Final Season",
    "Little Nightmares", "Little Nightmares Enhanced Edition", "Dead Rising", "Call of Duty: Black Ops - Multiplayer", "Due Process", "Tomb Raider",
    "Fallout Shelter", "For Honor", "Drug Dealer Simulator", "SEGA Mega Drive & Genesis Classics",
    "Goat Simulator", "RAGE", "DOOM", "Cuphead", "PC Building Simulator", "Geometry Dash", "Five Nights at Freddy's",
    "Plants vs. Zombies: Game of the Year", "Grand Theft Auto: Vice City", "Scott Pilgrim vs The World",
    "Call of Duty®: Black Ops Cold War", "Tomb Raider II", "Counter-Strike", "Overcooked",
    "60 Parsecs!", "Overcooked! 2", "Call of Duty: WWII", "Grand Theft Auto III", "SpeedRunners",
    "Call of Duty: Advanced Warfare", "Call of Duty®: Modern Warfare® 3 (2011) - Multiplayer",
    "Just Cause 3", "Fallout 2", "Rust - Staging Branch", "7 Days to Die",
    "Adventure Time: Pirates of the Enchiridion", "Alan Wake", "Alan Wake's American Nightmare", "Alice: Madness Returns",
    "Alien: Isolation", "American Truck Simulator", "Amnesia: The Dark Descent", "ARK: Survival Of The Fittest",
    "Arma 3", "Assassin's Creed Revelations", "Assassin's Creed® III", "Assassin's Creed III Remastered",
    "Assassin's Creed Liberation", "Assassin's Creed IV Black Flag", "Assassin's Creed Freedom Cry",
    "Assassin's Creed Unity", "Assassin's Creed Syndicate", "Assassin's Creed Odyssey", "Assassin's Creed Origins",
    "Assassin's Creed Rogue", "Assassin's Creed Valhalla", "Assassin's Creed® Chronicles: China",
    "Assassin's Creed® Chronicles: India", "Assassin's Creed® Chronicles: Russia", "Back 4 Blood",
    "Batman - The Telltale Series", "Batman: Arkham Asylum GOTY Edition", "Batman: Arkham City GOTY",
    "Batman™: Arkham Origins", "Batman™: Arkham Knight", "Batman: The Enemy Within - The Telltale Series",
    "Batman™: Arkham Origins Blackgate - Deluxe Edition", "BattleBit Remastered", "Battlefield 3™",
    "Battlefield 4™", "Battlefield™ 1", "Battlefield™ 2042", "Battlefield™ Hardline",
    "Battlefield™ V", "BioShock Remastered", "BioShock 2", "BioShock 2 Remastered", "BioShock Infinite",
    "Black Desert", "Borderlands 3", "Borderlands: The Pre-Sequel", "Brotato", "Burnout™ Paradise Remastered",
    "Call of Duty: Modern Warfare Remastered - Multiplayer", "Call of Duty: Modern Warfare Remastered (2017)",
    "Call of Duty®: Modern Warfare®", "Call of Duty®: Modern Warfare® II", "Call of Duty®: Modern Warfare® III",
    "Call of Duty®: Vanguard", "Capcom Fighting Collection", "Celeste", "Contra Anniversary Collection",
    "Control Ultimate Edition", "Counter-Strike: Condition Zero", "Counter-Strike: Condition Zero Deleted Scenes",
    "Counter-Strike: Source", "Crash Bandicoot™ N. Sane Trilogy", "Crusader Kings II", "Cult of the Lamb",
    "Darkest Dungeon®", "Days Gone", "DayZ", "Dead Cells",
    "Dead Island Definitive Edition", "Dead Island Retro Revenge", "Dead Island Riptide Definitive Edition",
    "Dead Rising 2", "Dead Rising 2: Off the Record", "Dead Rising 3", "Dead Rising 4", "Dead Space (2008)",
    "Dead Space 2", "Dead Space™ 3", "Deep Rock Galactic", "Deus Ex: Game of the Year Edition",
    "Deus Ex: Invisible War", "Deus Ex: Human Revolution - Director's Cut", "Deus Ex: The Fall",
    "Deus Ex: Mankind Divided™", "Dishonored", "Dishonored 2", "Don't Starve", "DOOM + DOOM II", "DOOM II",
    "DOOM 3", "DOOM 3: BFG Edition", "DOOM 3: Resurrection of Evil", "DOOM 64", "DOOM Eternal", "Dying Light",
    "Dying Light 2: Reloaded Edition", "Enter the Gungeon", "Escape Dead Island", "Euro Truck Simulator 2",
    "Exit the Gungeon", "Fable Anniversary", "Fallout 3 - Game of the Year Edition", "Fallout 76",
    "Fallout Tactics", "Far Cry 4", "Far Cry 5", "Far Cry 6", "Far Cry New Dawn",
    "Far Cry Primal", "Far Cry® 3", "Far Cry® 3 Blood Dragon", "Final DOOM", "FINAL FANTASY", "FINAL FANTASY II",
    "FINAL FANTASY III", "FINAL FANTASY IV", "FINAL FANTASY TYPE-0 HD", "FINAL FANTASY V", "FINAL FANTASY VI",
    "FINAL FANTASY VII", "FINAL FANTASY IX", "FINAL FANTASY XII THE ZODIAC AGE", "FINAL FANTASY XIII",
    "FINAL FANTASY XIII-2", "FINAL FANTASY XV WINDOWS EDITION", "Firewatch", "Five Nights at Freddy's 2",
    "Five Nights at Freddy's 3", "Friday the 13th: The Game", "Gang Beasts",
    "Garfield Kart", "Garfield Kart - Furious Racing", "Genital Jousting", "Golf It!", "Goose Goose Duck",
    "Grand Theft Auto III - The Definitive Edition", "Grand Theft Auto IV: The Complete Edition", "Grand Theft Auto V Enhanced",
    "Grand Theft Auto: San Andreas", "Grand Theft Auto: San Andreas - The Definitive Edition", "Grand Theft Auto: Vice City - The Definitive Edition",
    "Graveyard Keeper", "GRIS", "Grounded", "Grow Home", "Grow Up", "GTFO", "Hades", "Half-Life 2",
    "Half-Life 2: Deathmatch", "Half-Life Deathmatch: Source", "Half-Life: Blue Shift", "Half-Life: Opposing Force",
    "Half-Life: Source", "Halo Infinite", "Halo Wars: Definitive Edition", "Halo: Spartan Assault", "Halo: Spartan Strike",
    "Hand Simulator", "Heavy Rain", "Hellblade: Senua's Sacrifice", "Hellblade: Senua's Sacrifice VR Edition",
    "HELLDIVERS™", "Hitman: Codename 47", "Hitman 2: Silent Assassin", "Hitman: Contracts", "Hitman: Blood Money",
    "Hitman: Absolution", "Hitman GO: Definitive Edition", "HITMAN World of Assassination", "Hitman: Sniper Challenge",
    "HITMAN™", "HITMAN™ 2", "Hollow Knight", "Hollow Knight: Silksong", "Horizon Zero Dawn™ Complete Edition",
    "Hotline Miami", "Hotline Miami 2: Wrong Number", "House Flipper", "I Am Bread", "Injustice: Gods Among Us Ultimate Edition",
    "Injustice™ 2", "Just Cause 2", "Just Cause 4", "Keep Talking and Nobody Explodes", "Killing Floor",
    "Killing Floor 2", "Kingdom Come: Deliverance", "Lara Croft and the Guardian of Light", "Lara Croft and the Temple of Osiris",
    "Left 4 Dead", "LEGO® Batman™ 2: DC Super Heroes", "LEGO® Batman™ 3: Beyond Gotham", "LEGO® City Undercover",
    "LEGO® DC Super-Villains", "LEGO® Harry Potter: Years 1-4", "LEGO® Harry Potter: Years 5-7", "LEGO® Harry Potter™ Collection",
    "LEGO® Indiana Jones™ 2: The Adventure Continues", "LEGO® Jurassic World", "LEGO® MARVEL Super Heroes",
    "LEGO® MARVEL Super Heroes 2", "LEGO® MARVEL's Avengers", "LEGO® Pirates of the Caribbean The Video Game",
    "LEGO® Star Wars™ III: The Clone Wars™", "LEGO® STAR WARS™: The Force Awakens", "LEGO® Star Wars™: The Skywalker Saga",
    "LEGO® The Hobbit™", "LEGO® The Incredibles", "LEGO® The Lord of the Rings™", "LEGO® Worlds",
    "Life is Strange Remastered", "Life is Strange: Before the Storm Remastered", "Life is Strange: True Colors",
    "LIGHTNING RETURNS: FINAL FANTASY XIII", "Little Nightmares II", "Longvinter", "Mafia", "Mafia II (Classic)",
    "Mafia II: Definitive Edition", "Mafia III: Definitive Edition", "Mafia: Definitive Edition", "Marvel vs. Capcom: Infinite",
    "Marvel's Avengers - The Definitive Edition", "Marvel's Guardians of the Galaxy", "Marvel's Spider-Man: Miles Morales",
    "Mass Effect™ Legendary Edition", "Master Levels for DOOM II", "Max Payne", "Max Payne 2: The Fall of Max Payne",
    "Max Payne 3", "Metro 2033", "Metro 2033 Redux", "Metro Exodus", "Metro Exodus Enhanced Edition",
    "Metro: Last Light Complete Edition", "Metro: Last Light Redux", "Mirror's Edge", "Mirror's Edge™ Catalyst",
    "Monopoly Plus", "Moonlighter", "Mortal Kombat 11", "Mortal Kombat X", "My Friend Pedro",
    "Need for Speed™", "Need for Speed™ Heat", "Need for Speed™ Hot Pursuit Remastered", "Need for Speed™ Most Wanted",
    "Need for Speed™ Payback", "Need for Speed™ Rivals", "Need for Speed™ Unbound", "New Tales from the Borderlands",
    "No Man's Sky", "Ori and the Blind Forest", "Ori and the Blind Forest: Definitive Edition", "Ori and the Will of the Wisps",
    "Outlast", "Outlast 2", "PAYDAY 2", "PICO PARK", "Planet Coaster", "Plants vs. Zombies: Battle for Neighborville",
    "Portal 2 - The Final Hours", "Prince of Persia", "Prince of Persia: The Sands of Time", "Prince of Persia: Warrior Within",
    "Prince of Persia: The Two Thrones", "Prince of Persia: The Forgotten Sands", "Prototype", "PROTOTYPE 2",
    "Punch Club", "RAGE 2", "Rayman Legends", "Rayman Origins", "Rayman: Raving Rabbids", "Red Dead Redemption",
    "Resident Evil", "Resident Evil 0", "Resident Evil 2", "Resident Evil 3", "Resident Evil 4 (2005)",
    "Resident Evil 5", "Resident Evil 6", "Resident Evil 7 Biohazard", "Resident Evil Re:Verse", "RESIDENT EVIL RESISTANCE",
    "Resident Evil Revelations", "Resident Evil Revelations 2", "Resident Evil Village", "Return to Castle Wolfenstein",
    "Rise of the Tomb Raider", "Risk of Rain (2013)", "Saints Row 2", "Saints Row: The Third",
    "Saints Row IV", "Saints Row The Third Remastered", "Saints Row: Gat out of Hell", "Scooby-Doo! & Looney Tunes Cartoon Universe: Adventure",
    "Scribblenauts Unlimited", "Scribblenauts Unmasked", "Sea of Thieves", "Shadow of the Tomb Raider",
    "Sid Meier's Civilization VI", "Slay the Spire", "Slime Rancher 2",
    "Sniper Elite", "Sniper Elite V2", "Sniper Elite 3", "Sniper Elite 4", "Sniper Elite 5", "Sniper Elite V2 Remastered",
    "Sonic & All-Stars Racing Transformed Collection", "Sonic Adventure DX", "Sonic Adventure™ 2", "Sonic and SEGA All Stars Racing",
    "Sonic CD", "Sonic Forces", "Sonic Generations", "Sonic Lost World", "Sonic Mania", "SONIC THE HEDGEHOG 4 Episode I",
    "SONIC THE HEDGEHOG 4 Episode II", "Split Fiction", "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated",
    "Spore", "STAR WARS Jedi: Survivor™", "STAR WARS™ Battlefront™", "STAR WARS™ Battlefront™ II", "STAR WARS™: Squadrons",
    "Starbound", "Stick Fight: The Game", "Street Fighter 30th Anniversary Collection",
    "Street Fighter V", "Subnautica", "Subnautica: Below Zero", "Suicide Squad: Kill the Justice League",
    "Sunset Overdrive", "Surgeon Simulator", "Tales from the Borderlands",
    "Team Fortress Classic", "Team Sonic Racing™", "The Binding of Isaac: Rebirth", "The Crew 2",
    "The Elder Scrolls III: Morrowind", "The Elder Scrolls IV: Oblivion Game of the Year Edition (2009)",
    "The Elder Scrolls V: Skyrim Special Edition", "The Evil Within", "The Evil Within 2", "THE GAME OF LIFE",
    "The Lab", "The Last of Us™ Part I", "The LEGO® Movie - Videogame", "The LEGO® Movie 2 - Videogame",
    "The LEGO® NINJAGO® Movie Video Game", "The Outer Worlds: Spacer's Choice Edition", "The Sims™ 4",
    "The Walking Dead: Michonne", "The Walking Dead: The Telltale Definitive Series", "The Wolf Among Us",
    "theHunter: Call of the Wild™", "Thief", "Thief Gold", "Thief: Deadly Shadows", "Thief™ II: The Metal Age",
    "Tiny Tina's Wonderlands", "Titanfall® 2", "Tom Clancy's EndWar", "Tom Clancy's Ghost Recon",
    "Tom Clancy's Ghost Recon: Desert Siege", "Tom Clancy's Ghost Recon: Island Thunder", "Tom Clancy's Ghost Recon Future Soldier",
    "Tom Clancy's Ghost Recon® Wildlands", "Tom Clancy's Rainbow Six 3: Gold Edition", "Tom Clancy's Rainbow Six 3: Athena Sword",
    "Tom Clancy's Rainbow Six: Lockdown", "Tom Clancy's Rainbow Six: Vegas",
    "Tom Clancy's Rainbow Six: Vegas 2", "Tom Clancy's Splinter Cell", "Tom Clancy's Splinter Cell: Chaos Theory",
    "Tom Clancy's Splinter Cell: Double Agent", "Tom Clancy's Splinter Cell: Conviction", "Tom Clancy's Splinter Cell Blacklist",
    "Tom Clancy's The Division", "Tomb Raider III: Adventures of Lara Croft",
    "Tomb Raider: The Last Revelation (1999)", "Tomb Raider: Chronicles (2000)", "Tomb Raider (VI): The Angel of Darkness (2003)",
    "Tomb Raider I-III Remastered Starring Lara Croft", "Tomb Raider: Anniversary", "Tomb Raider: Legend",
    "Town of Salem", "Trials Evolution Gold Edition", "Trials Fusion", "Trials Rising", "Ultimate Chicken Horse",
    "Ultimate Marvel vs. Capcom 3", "Ultra Street Fighter IV", "Umbrella Corps", "UNCHARTED™: Legacy of Thieves Collection",
    "Undertale", "Unravel", "Unravel Two", "Watch Dogs: Legion", "Watch_Dogs", "Watch_Dogs 2", "Witch It",
    "Wizard of Legend", "Wolfenstein 3D", "Wolfenstein 3D: Spear of Destiny", "Wolfenstein II: The New Colossus",
    "Wolfenstein: Enemy Territory", "Wolfenstein: The New Order", "Wolfenstein: The Old Blood", "Wolfenstein: Youngblood",
    "Worms", "Worms Armageddon", "Worms Blast", "Worms Clan Wars", "Worms Crazy Golf", "Worms Pinball",
    "Worms Reloaded", "Worms Revolution", "Worms Rumble", "Worms Ultimate Mayhem", "Worms W.M.D",
    "Worms World Party Remastered", "XCOM 2", "Tomb Raider IV-VI Remastered", "Frostpunk",
    "Company of Heroes 2", "Dead Space", "DEATHLOOP", "Destroy All Humans! 2 - Reprobed", "High on Life", "Prey",
    "Pummel Party", "R.E.P.O", "Saints Row", "Sleeping Dogs: Definitive Edition", "SOMA",
    "SpongeBob SquarePants: The Cosmic Shake", "SOUTH PARK: SNOW DAY!", "The Elder Scrolls® Online",
    "Yooka-Laylee", "Yooka-Laylee and the Impossible Lair",
    "Flight Simulator X Steam Edition", "Death Stranding Directors Cut", "Escape Simulator",
    "Five Nights at Freddy's: Sister Location", "Five Nights at Freddy's 4",

    // New games (pending photos, times, achievements)
    "Gamble With Your Friends", "Cloverpit", "KEEP GAMBLING", "Within of Static - Ashburg Rental",
    "TCG Card Shop Simulator", "Fears to Fathom - Scratch Creek", "Within of Static - Northgate Mall",
    "Tales Beyond The Tomb - No Witnesses", "Tales Beyond The Tomb - Route 86", "Tales Beyond The Tomb - White Silence",
    "A Game About Digging A Hole", "Riders Republic", "THE GAME OF LIFE 2", "The Texas Chain Saw Massacre",
    "STAR WARS Battlefront (Classic, 2004)", "Planet Zoo", "Who's Your Daddy?!", "Black Mesa", "POSTAL 2",
    "The Binding of Isaac", "Dragon Age: Origins - Ultimate Edition", "FINAL FANTASY VIII",
    "STAR WARS Knights of the Old Republic", "Fallout 3", "Star Wars: Battlefront 2 (Classic, 2005)",
    "Tales Beyond The Tomb - The Last Vigil", "Backrooms: Escape Together", "Tales Beyond The Tomb - The Farm's Secret",
    "Tales Beyond The Tomb - Pineville Night Stalker", "The Stanley Parable: Ultra Deluxe",
    "Resident Evil (1996)", "Resident Evil 3 Nemesis (1999)", "Resident Evil 2 (1998)",
    "EA SPORTS Madden NFL 26", "Hellblade II: Senua's Saga", "Sonic Colors: Ultimate", "Mortal Kombat 1",
    "Sonic Origins", "Gotham Knights", "Hello Neighbor 2", "Overcooked! All You Can Eat",
    "FINAL FANTASY VIII - REMASTERED", "Dishonored: Death of the Outsider", "State of Decay 2",
    "FINAL FANTASY IV: THE AFTER YEARS", "State of Decay: Year-One", "Final Fantasy IV (3D Remake)",
    "The Long Dark", "Final Fantasy III (3D Remake)", "L.A. Noire", "Manhunt", "Balatro",
    "Tom Clancy's Splinter Cell: Pandora Tomorrow", "Tom Clancy's The Division 2",
    "F.E.A.R.: Perseus Mandate", "F.E.A.R.: Extraction Point", "F.E.A.R. 3", "F.E.A.R.",
    "F.E.A.R.2: Project Origin", "Sons Of The Forest", "Dead Island 2", "Risk of Rain 2", "Battlefield 6"
];

// Populate the database
allGames.forEach(game => {
    gameDatabase[game] = {
        title: game,
        timeToBeat: manualGameTimes[game] || null,
        category: getTimeCategory(manualGameTimes[game] || null),
        releaseYear: releaseDates[game] || null
    };
});

function getTimeCategory(hours) {
    if (!hours) return 'unknown';
    if (hours <= 5) return 'short';
    if (hours <= 20) return 'medium';
    return 'long';
}

// Export for use in the web app
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { gameDatabase, manualGameTimes, releaseDates };
} else {
    window.gameDatabase = gameDatabase;
    window.releaseDates = releaseDates;
}